packages:
  - 'HDmaster'
  - 'orderking-customers'
  - 'orderking-partners'
  - 'orderking-riders'
  - 'Apps-integration-'
  - 'packages/*'
allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  esbuild: true
  protobufjs: true
minimumReleaseAgeExclude:
  - framer-motion@13.4.5
  - motion-dom@13.4.5
  - '@google-cloud/bigquery@9.2.0'
  - playwright-core@1.64.0
  - playwright@1.64.0
  - geolib@4.0.0
