/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettlementsRouteImport } from './routes/settlements'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeliveryIdRouteImport } from './routes/delivery.$id'
import { Route as ApiSecurityGpsPingRouteImport } from './routes/api/security/gps-ping'
import { Route as ApiSecurityDevicePostureRouteImport } from './routes/api/security/device-posture'
import { Route as ApiSecurityDeviceIntegrityRouteImport } from './routes/api/security/device-integrity'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementsRoute = SettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIdRoute = DeliveryIdRouteImport.update({
  id: '/delivery/$id',
  path: '/delivery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityGpsPingRoute = ApiSecurityGpsPingRouteImport.update({
  id: '/api/security/gps-ping',
  path: '/api/security/gps-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityDevicePostureRoute =
  ApiSecurityDevicePostureRouteImport.update({
    id: '/api/security/device-posture',
    path: '/api/security/device-posture',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSecurityDeviceIntegrityRoute =
  ApiSecurityDeviceIntegrityRouteImport.update({
    id: '/api/security/device-integrity',
    path: '/api/security/device-integrity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/settlements': typeof SettlementsRoute
  '/support': typeof SupportRoute
  '/delivery/$id': typeof DeliveryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/security/device-integrity': typeof ApiSecurityDeviceIntegrityRoute
  '/api/security/device-posture': typeof ApiSecurityDevicePostureRoute
  '/api/security/gps-ping': typeof ApiSecurityGpsPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/settlements': typeof SettlementsRoute
  '/support': typeof SupportRoute
  '/delivery/$id': typeof DeliveryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/security/device-integrity': typeof ApiSecurityDeviceIntegrityRoute
  '/api/security/device-posture': typeof ApiSecurityDevicePostureRoute
  '/api/security/gps-ping': typeof ApiSecurityGpsPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/earnings': typeof EarningsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/settlements': typeof SettlementsRoute
  '/support': typeof SupportRoute
  '/delivery/$id': typeof DeliveryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/security/device-integrity': typeof ApiSecurityDeviceIntegrityRoute
  '/api/security/device-posture': typeof ApiSecurityDevicePostureRoute
  '/api/security/gps-ping': typeof ApiSecurityGpsPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/earnings'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/settlements'
    | '/support'
    | '/delivery/$id'
    | '/api/auth/$'
    | '/api/security/device-integrity'
    | '/api/security/device-posture'
    | '/api/security/gps-ping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/earnings'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/settlements'
    | '/support'
    | '/delivery/$id'
    | '/api/auth/$'
    | '/api/security/device-integrity'
    | '/api/security/device-posture'
    | '/api/security/gps-ping'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/earnings'
    | '/history'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/safety'
    | '/settlements'
    | '/support'
    | '/delivery/$id'
    | '/api/auth/$'
    | '/api/security/device-integrity'
    | '/api/security/device-posture'
    | '/api/security/gps-ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  EarningsRoute: typeof EarningsRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  SettlementsRoute: typeof SettlementsRoute
  SupportRoute: typeof SupportRoute
  DeliveryIdRoute: typeof DeliveryIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSecurityDeviceIntegrityRoute: typeof ApiSecurityDeviceIntegrityRoute
  ApiSecurityDevicePostureRoute: typeof ApiSecurityDevicePostureRoute
  ApiSecurityGpsPingRoute: typeof ApiSecurityGpsPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlements': {
      id: '/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof SettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/$id': {
      id: '/delivery/$id'
      path: '/delivery/$id'
      fullPath: '/delivery/$id'
      preLoaderRoute: typeof DeliveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/gps-ping': {
      id: '/api/security/gps-ping'
      path: '/api/security/gps-ping'
      fullPath: '/api/security/gps-ping'
      preLoaderRoute: typeof ApiSecurityGpsPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/device-posture': {
      id: '/api/security/device-posture'
      path: '/api/security/device-posture'
      fullPath: '/api/security/device-posture'
      preLoaderRoute: typeof ApiSecurityDevicePostureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/device-integrity': {
      id: '/api/security/device-integrity'
      path: '/api/security/device-integrity'
      fullPath: '/api/security/device-integrity'
      preLoaderRoute: typeof ApiSecurityDeviceIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  EarningsRoute: EarningsRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  SettlementsRoute: SettlementsRoute,
  SupportRoute: SupportRoute,
  DeliveryIdRoute: DeliveryIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSecurityDeviceIntegrityRoute: ApiSecurityDeviceIntegrityRoute,
  ApiSecurityDevicePostureRoute: ApiSecurityDevicePostureRoute,
  ApiSecurityGpsPingRoute: ApiSecurityGpsPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
