export const en = {
  app: {
    name: "Order King Partner",
    tagline: "Your kitchen. Your orders. Your settlement.",
    simulated: "SIMULATED",
    real: "REAL",
    verified: "VERIFIED",
    notConnected: "NOT CONNECTED",
    estimate: "Estimate",
    stale: "CONNECTION LOST — DATA MAY BE OUTDATED",
    simulatedHint: "DEMO RESTAURANT. Not a live kitchen.",
  },
  auth: {
    signIn: "Sign in", signUp: "Create account", signOut: "Sign out", email: "Email", password: "Password", name: "Your name",
    continueGoogle: "Continue with Google", continueX: "Continue with X", orEmail: "Or use email", haveAccount: "Already have an account?", noAccount: "New kitchen?", working: "Please wait…", error: "Could not sign in. Check your details and try again.", passwordHint: "At least 8 characters",
  },
  landing: {
    kicker: "Restaurant operating system", title: "Run the kitchen. Keep every rupee visible.",
    body: "Accept orders, mark food ready, and see exactly what you will be paid — commission, restaurant discounts and platform-funded offers, separately.",
    cta: "Partner sign in", forOwners: "Built for small kitchens in Karimganj and beyond. Large buttons. Plain language. No hidden deductions.",
  },
  nav: { home: "Home", orders: "Orders", kitchen: "Kitchen", menu: "Menu", more: "More", promotions: "Offers", settlements: "Settlement", analytics: "Analytics", reviews: "Reviews", notifications: "Alerts", assistant: "Assistant", hours: "Hours", settings: "Settings", onboarding: "Restaurant profile", availability: "Availability" },
  dashboard: { today: "Today", orders: "Orders", sales: "Sales", aov: "Average order", accepted: "Accepted", pending: "Waiting", cancelled: "Cancelled", refunds: "Refunds", settlement: "Estimated settlement", prep: "Prep performance", unavailable: "Unavailable items", rating: "Customer rating", repeat: "Repeat customers", attention: "What needs attention", noAttention: "Nothing waiting. Kitchen is clear.", greeting: "Good to see you", attnPending: "{n} order(s) waiting for acceptance", attnUnavailable: "{n} item(s) unavailable", attnClosing: "Restaurant closing in {n} minutes", attnVerify: "Kitchen is {status} — not shown to customers", attnFssai: "FSSAI number missing", attnDelay: "{n} delayed order(s)", attnSettle: "Settlement available", open: "Open", closed: "Closed", seeOrders: "Open live orders" },
  orders: { incoming: "Incoming", live: "Live orders", history: "History", accept: "Accept", reject: "Reject", preparing: "Start preparing", ready: "Mark ready", rejectTitle: "Why are you rejecting?", rejectHint: "A reason is required. Silent rejection is not allowed.", special: "Special instructions", payment: "Payment", cod: "Cash on delivery", paid: "Paid online", total: "Total", discount: "Discount", platformPromo: "Platform-funded offer", restaurantPromo: "Restaurant-funded offer", empty: "No orders right now.", received: "Received", items: "Items", prepTime: "Prep time", simulateRider: "Advance rider (simulated)", simulateRiderHint: "Only for simulated kitchens. Real rider assignment comes from the rider system." },
  kitchen: { title: "Kitchen mode", new: "NEW", accepted: "ACCEPTED", preparing: "PREPARING", ready: "READY", pickup: "PICKUP", soundOn: "Sound on", soundOff: "Sound off", empty: "No tickets." },
  menu: { title: "Menu", categories: "Categories", addCategory: "Add category", addItem: "Add item", duplicate: "Duplicate", soldOut: "Sold out", available: "Available", unavailable: "Temporarily unavailable", scheduled: "Scheduled", veg: "Veg", nonveg: "Non-veg", egg: "Contains egg", price: "Price", variants: "Sizes / variants", addons: "Add-ons", save: "Save", edit: "Edit", bulk: "Bulk availability", bulkSoldOut: "Mark selected sold out", bulkAvailable: "Mark selected available", addAddon: "Add add-on", recommended: "Recommended", noItems: "No items yet. Add your first dish.", name: "Name", description: "Description", prep: "Prep minutes" },
  promotions: { title: "Offers", restaurantFunded: "Restaurant-funded", platformFunded: "Platform-funded", estimate: "At {n} orders/day, this offer may reduce restaurant revenue by approximately {amount}. This is an estimate.", activate: "Activate", pause: "Pause", create: "New offer", percent: "Percentage off", fixed: "Fixed amount off", item: "Item discount", bogo: "Buy one get one", minOrder: "Minimum order", maxDiscount: "Maximum discount" },
  settlements: { title: "Settlement", payable: "Current payable", pending: "Pending settlement", completed: "Completed", exportCsv: "Download CSV", exportJson: "Download JSON", food: "Food value", restDisc: "Restaurant discount", commission: "Commission", packing: "Packaging", platformDisc: "Platform-funded discount", refund: "Refund adjustment", payableLine: "Restaurant payable", other: "Other authorised deduction", empty: "No settlement lines yet.", simulatedNote: "Simulated figures. Not a real payout.", formula: "How payable is calculated", formulaHint: "Food + packing − restaurant discount − commission − other authorised deduction + platform-funded offer ± refund = restaurant payable." },
  analytics: { title: "Analytics", sales: "Sales", orders: "Orders", items: "Items", time: "Time", customers: "Customers", promos: "Offers", real: "REAL DATA", simulated: "SIMULATED DATA", estimated: "ESTIMATED DATA", best: "Best sellers", low: "Low performers", peak: "Peak hours", avgPrep: "Average preparation" },
  reviews: { title: "Reviews", respond: "Reply", empty: "No reviews yet.", cannotDelete: "Reviews cannot be deleted or altered by the restaurant." },
  assistant: { title: "Kitchen assistant", placeholder: "Ask about today’s sales, slow items, or your settlement…", send: "Ask", disclaimer: "Answers use only this restaurant’s authorised numbers. The assistant will not invent financial figures.", unavailable: "AI is not connected in this environment.", examples: "What were my best-selling items today?|Which hours were busiest?|Explain my settlement.|Which items are often unavailable?" },
  onboarding: { title: "Tell us about your kitchen", demoCta: "Explore a simulated kitchen", demoHint: "Loads labelled DEMO data so you can practise orders. It is not a live restaurant.", realCta: "Register my restaurant", status: "Verification status", notVerified: "Not verified. Customers will not see this kitchen until a platform admin verifies it.", name: "Restaurant name", displayName: "Display name", owner: "Owner name", phone: "Phone", email: "Email", address: "Address", landmark: "Landmark", cuisine: "Cuisine", vegStatus: "Food type", description: "Description", gst: "GSTIN", fssai: "FSSAI number", pan: "PAN", bank: "Bank account", ifsc: "IFSC", submit: "Submit for review", saveDraft: "Save draft", submitted: "Submitted. A platform admin will review your documents.", documents: "Documents", storageHint: "File storage is NOT CONNECTED. The file is recorded locally with PENDING verification." },
  hours: { title: "Hours", closed: "Closed", emergency: "Emergency close", vacation: "Vacation mode", split: "Split shift", save: "Save hours", peak: "Peak prep minutes", day0: "Sunday", day1: "Monday", day2: "Tuesday", day3: "Wednesday", day4: "Thursday", day5: "Friday", day6: "Saturday" },
  settings: { title: "Settings", language: "Language", english: "English", bengali: "বাংলা", commission: "Commission", staff: "Staff", financialLocked: "Bank and commission settings are restricted for your role.", role: "Role", add: "Add", adapters: "Connections", snapshotHint: "Snapshot per order. Changing commission later does not rewrite history." },
  notifications: { title: "Alerts", empty: "No alerts.", smsOff: "SMS is not connected.", waOff: "WhatsApp is not connected.", markRead: "Mark read" },
  common: { save: "Save", cancel: "Cancel", confirm: "Confirm", loading: "Loading…", retry: "Try again", search: "Search", minutes: "min", today: "Today", week: "This week", month: "This month", yes: "Yes", no: "No", required: "Required", close: "Close", back: "Back", next: "Next", filter: "Filter", all: "All", none: "None" },
  rejectReasons: { item_unavailable: "Item unavailable", kitchen_overloaded: "Kitchen overloaded", restaurant_closed: "Restaurant closed", technical_issue: "Technical issue", other: "Other" },
  status: { DRAFT: "Draft", SUBMITTED: "Submitted", UNDER_REVIEW: "Under review", VERIFIED: "Verified", REJECTED: "Rejected", SUSPENDED: "Suspended", PLACED: "New", ACCEPTED: "Accepted", PREPARING: "Preparing", READY: "Ready", RIDER_ASSIGNED: "Rider assigned", PICKED_UP: "Picked up", ON_THE_WAY: "On the way", DELIVERED: "Delivered", CANCELLED: "Cancelled", REFUNDED: "Refunded", PARTIAL_REFUND: "Partial refund", FAILED_PAYMENT: "Payment failed", DELIVERY_FAILED: "Delivery failed" },
} as const;

type DeepString<T> = T extends string ? string : { [K in keyof T]: DeepString<T[K]> };
export type MessageTree = DeepString<typeof en>;
export type MessageKeySource = typeof en;
