export const en = {
  brandFallback: "OrderKing",
  common: {
    search: "Explore", cart: "My Cart", account: "My Account", orders: "My Orders", home: "Home", offers: "Offers", support: "Support", signIn: "Sign in", signOut: "Sign out", save: "Save", cancel: "Cancel", close: "Close", add: "Add", added: "Added", remove: "Remove", next: "Continue", retry: "Try again", loading: "Loading", veg: "Veg", nonVeg: "Non-veg", sample: "Sample", closed: "Closed", open: "Open", new: "New", ad: "Ad", viewAll: "See all", language: "Language", english: "English", bengali: "বাংলা", assamese: "অসমীয়া", hindi: "हिन्दी", offline: "You are offline. Some actions will wait until you reconnect.", error: "Something went wrong", empty: "Nothing here yet",
  },
  home: { deliveringTo: "Delivering to you", changeLocation: "Change", searchPlaceholder: "Search biryani, momo, pizza…", categories: "Categories", bestOffers: "Best offers", popular: "Popular near you", bestRated: "Best rated", fast: "Fast delivery", budget: "Budget friendly", newRestaurants: "New kitchens", recommended: "Recommended for you", reorder: "Order again", favourites: "Your favourites", sampleBanner: "Sample catalogue. These kitchens are not live vendors. Every card is marked Sample until a real kitchen is verified.", noResults: "No kitchens match those filters.", etaMin: "{n} min", deliveryFrom: "Delivery {fee}", minOrder: "Min {amount}", openNow: "Open now", vegOnly: "Pure veg", hasOffer: "Offers" },
  location: { title: "Delivery location", useCurrent: "Use current location", locating: "Finding you…", saved: "Saved addresses", areas: "Service areas", manual: "Enter an address", line1: "House / street", landmark: "Landmark", area: "Area", instructions: "Delivery notes", labelHome: "Home", labelWork: "Work", labelOther: "Other", saveAddress: "Save address", outside: "That point is outside the current service area. You can still browse a listed area.", geoDenied: "Location permission was denied. Pick an area instead.", simulatedPin: "Sample map pin — not a live GPS track." },
  restaurant: { minOrder: "Minimum {amount}", delivery: "Delivery {fee}", eta: "{n} minutes", closedNotice: "This kitchen is closed right now. You can browse the menu.", sampleNotice: "Sample kitchen for development. Not a live vendor.", recommended: "Recommended", add: "Add", customise: "Customise", unavailable: "Not available", spicy: "Spicy", bestseller: "Bestseller", searchMenu: "Search this menu" },
  customize: { title: "Customise", required: "Required", optional: "Optional", size: "Choose", instructions: "Any kitchen note?", instructionsPlaceholder: "Less oil, no onion…", quantity: "Quantity", addFor: "Add {amount}", update: "Update item" },
  cart: { title: "My Cart", empty: "Your cart is empty", emptyHint: "Add something from a kitchen to see the full price here.", browse: "Browse kitchens", replaceTitle: "Start a new cart?", replaceBody: "Your cart has items from {name}. Adding this will clear that cart.", replace: "Replace cart", keep: "Keep current cart", from: "From {name}", item: "item", items: "items", subtotal: "Subtotal", toPay: "To pay", view: "View cart", checkout: "Checkout", coupon: "Have a code?", apply: "Apply", applied: "Applied", invalidCoupon: "This code cannot be used on this order.", clear: "Clear cart", savings: "You save {amount}", includesTax: "Food prices include applicable kitchen taxes.", minOrder: "This kitchen needs a minimum of {amount}." },
  checkout: { title: "Checkout", address: "Deliver to", addAddress: "Add address", pay: "Pay", cod: "Cash on delivery", codHint: "Pay the rider in cash or UPI at the door. No card details collected.", upi: "UPI", upiUnavailable: "Online UPI is not live. A payment provider (Razorpay or Cashfree) still needs KYC and keys.", upiSandbox: "Sandbox UPI (not a real transfer)", upiSandboxHint: "Marks the order as paid in this development environment only. No money moves.", place: "Place order · {amount}", placing: "Placing order…", signInFirst: "Sign in to place this order.", needAddress: "Add a delivery address to continue.", failed: "Could not place the order. No charge was made.", notes: "Note for the kitchen", blocked: "This order cannot be placed yet.", upiVpa: "UPI ID (sandbox)", upiVpaPlaceholder: "name@okaxis", upiConfirm: "Confirm sandbox payment", sandboxBadge: "Sandbox — no money moves" },
  orders: { title: "My Orders", empty: "No orders yet", emptyHint: "When you place an order, it will show up here with live status.", active: "Active", past: "Past", reorder: "Order again", track: "Track", help: "Help", placed: "Order confirmed", accepted: "Kitchen accepted", preparing: "Preparing", ready: "Ready", riderAssigned: "Rider assigned", pickedUp: "Picked up", onTheWay: "On the way", delivered: "Delivered", rejected: "Kitchen declined", cancelled: "Cancelled", refunded: "Refunded", failed: "Payment failed", deliveryFailed: "Delivery failed", otp: "Delivery PIN {code}", otpHint: "Share this PIN only with the rider at your door.", simulate: "Advance sample kitchen status", simulateHint: "Sample kitchens can step forward so you can test tracking. This is not a live dispatch.", noGps: "Live rider GPS is not shown. Coordinates would only appear after a real rider app is connected.", cancelOrder: "Cancel order", cancelPolicy: "You can cancel until the kitchen starts preparing.", invoice: "Bill", total: "Total", copyId: "Order {id}" },
  quote: { FOOD: "Food", RESTAURANT_DISCOUNT: "Kitchen discount", PLATFORM_DISCOUNT: "Platform discount", PACKAGING: "Packaging", DELIVERY: "Delivery", SERVICE: "Service fee", TAX: "Tax", TOTAL: "To pay" },
  account: { title: "My Account", guest: "Welcome, King", guestHint: "Sign in to manage your addresses, orders, and KingPay wallet.", profile: "Profile", name: "Name", phone: "Phone", email: "Email", addresses: "Addresses", favourites: "Favourites", offers: "Offers", loyalty: "{name} points", loyaltyHint: "Points are a loyalty ledger, not a stored-value wallet or cash.", points: "{n} points", notifications: "Notifications", privacy: "Privacy", terms: "Terms", refunds: "Refunds", about: "About {name}", delete: "Request account deletion", deleteHint: "We will record the request. A person still has to complete legal deletion after launch.", deleteDone: "Deletion request recorded.", language: "App language", saved: "Saved", notificationsEmpty: "No notifications yet." },
  offers: { title: "Offers", empty: "No offers on this order yet", fundedByRestaurant: "Funded by the kitchen", fundedByPlatform: "Funded by the platform", fundedByShared: "Shared by kitchen and platform", min: "Min order {amount}" },
  support: { title: "Support", hint: "Tell us what happened. We will not auto-refund unless the policy for this order allows it.", topic: "Topic", topics: { where: "Where is my order?", issue: "Order issue", missing: "Missing item", wrong: "Wrong item", payment: "Payment issue", cancel: "Cancellation", refund: "Refund", restaurant: "Kitchen issue", delivery: "Delivery issue", other: "Other" }, message: "Message", send: "Send", sent: "Request sent", tickets: "Your requests", whatsapp: "WhatsApp", whatsappHint: "Opens a chat with support. This is not a live kitchen line until a number is connected.", whatsappMissing: "WhatsApp is an adapter. No support number is connected yet." },
  auth: { title: "Sign in to {name}", subtitle: "Use Google, X, or email. Phone OTP needs an SMS provider, which is not connected yet.", google: "Continue with Google", x: "Continue with X", email: "Email", password: "Password", name: "Name", emailSignIn: "Sign in with email", emailSignUp: "Create account", switchToSignUp: "Need an account? Create one", switchToSignIn: "Already have an account? Sign in", phoneSoon: "Phone OTP", phoneSoonHint: "Adapter is ready. MSG91 / DLT sender ID is an external activation step — not available in this environment.", error: "Sign-in failed. Try again.", disabled: "Sign-in is disabled in this environment." },
  legal: { privacy: "Privacy notice", terms: "Terms of use", refunds: "Refunds and cancellation", grievance: "Grievance" },
  a11y: { skip: "Skip to menu", openMenu: "Open menu", closeDialog: "Close dialog", decreaseQty: "Decrease quantity", increaseQty: "Increase quantity" },
} as const;

type DeepStringify<T> = { [K in keyof T]: T[K] extends string ? string : DeepStringify<T[K]> };
export type MessageTree = DeepStringify<typeof en>;
