/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KingPayRouteImport } from './routes/king-pay'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as TrackingDispatchJobIdRouteImport } from './routes/tracking.$dispatchJobId'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundsRouteImport } from './routes/legal/refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as DevBrandRouteImport } from './routes/dev/brand'
import { Route as AppFounderCommandRouteImport } from './routes/app/founder-command'
import { Route as ApiReferralsRouteImport } from './routes/api/referrals'
import { Route as ApiSecurityDevicePostureRouteImport } from './routes/api/security/device-posture'
import { Route as ApiSecurityDeviceIntegrityRouteImport } from './routes/api/security/device-integrity'
import { Route as ApiRazorpayVerifyRouteImport } from './routes/api/razorpay/verify'
import { Route as ApiRazorpayCreateOrderRouteImport } from './routes/api/razorpay/create-order'
import { Route as ApiLoansApplyRouteImport } from './routes/api/loans/apply'
import { Route as ApiEscrowStatusRouteImport } from './routes/api/escrow/status'
import { Route as ApiBbpsPayBillRouteImport } from './routes/api/bbps/pay-bill'
import { Route as ApiBbpsFetchBillRouteImport } from './routes/api/bbps/fetch-bill'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAffiliatesOffersRouteImport } from './routes/api/affiliates/offers'
import { Route as ApiAffiliateClickRouteImport } from './routes/api/affiliate/click'
import { Route as ApiAdminTestConnectionRouteImport } from './routes/api/admin/test-connection'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiOrdersOrderIdStreamRouteImport } from './routes/api/orders/$orderId/stream'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KingPayRoute = KingPayRouteImport.update({
  id: '/king-pay',
  path: '/king-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingDispatchJobIdRoute = TrackingDispatchJobIdRouteImport.update({
  id: '/tracking/$dispatchJobId',
  path: '/tracking/$dispatchJobId',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBrandRoute = DevBrandRouteImport.update({
  id: '/dev/brand',
  path: '/dev/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFounderCommandRoute = AppFounderCommandRouteImport.update({
  id: '/app/founder-command',
  path: '/app/founder-command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsRoute = ApiReferralsRouteImport.update({
  id: '/api/referrals',
  path: '/api/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSecurityDevicePostureRoute =
  ApiSecurityDevicePostureRouteImport.update({
    id: '/api/security/device-posture',
    path: '/api/security/device-posture',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSecurityDeviceIntegrityRoute =
  ApiSecurityDeviceIntegrityRouteImport.update({
    id: '/api/security/device-integrity',
    path: '/api/security/device-integrity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRazorpayVerifyRoute = ApiRazorpayVerifyRouteImport.update({
  id: '/api/razorpay/verify',
  path: '/api/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayCreateOrderRoute = ApiRazorpayCreateOrderRouteImport.update({
  id: '/api/razorpay/create-order',
  path: '/api/razorpay/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoansApplyRoute = ApiLoansApplyRouteImport.update({
  id: '/api/loans/apply',
  path: '/api/loans/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEscrowStatusRoute = ApiEscrowStatusRouteImport.update({
  id: '/api/escrow/status',
  path: '/api/escrow/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBbpsPayBillRoute = ApiBbpsPayBillRouteImport.update({
  id: '/api/bbps/pay-bill',
  path: '/api/bbps/pay-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBbpsFetchBillRoute = ApiBbpsFetchBillRouteImport.update({
  id: '/api/bbps/fetch-bill',
  path: '/api/bbps/fetch-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliatesOffersRoute = ApiAffiliatesOffersRouteImport.update({
  id: '/api/affiliates/offers',
  path: '/api/affiliates/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateClickRoute = ApiAffiliateClickRouteImport.update({
  id: '/api/affiliate/click',
  path: '/api/affiliate/click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestConnectionRoute = ApiAdminTestConnectionRouteImport.update({
  id: '/api/admin/test-connection',
  path: '/api/admin/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersOrderIdStreamRoute = ApiOrdersOrderIdStreamRouteImport.update({
  id: '/api/orders/$orderId/stream',
  path: '/api/orders/$orderId/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/king-pay': typeof KingPayRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/offers': typeof OffersRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tutor': typeof TutorRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/app/founder-command': typeof AppFounderCommandRoute
  '/dev/brand': typeof DevBrandRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/r/$slug': typeof RSlugRoute
  '/tracking/$dispatchJobId': typeof TrackingDispatchJobIdRoute
  '/account/': typeof AccountIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/test-connection': typeof ApiAdminTestConnectionRoute
  '/api/affiliate/click': typeof ApiAffiliateClickRoute
  '/api/affiliates/offers': typeof ApiAffiliatesOffersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bbps/fetch-bill': typeof ApiBbpsFetchBillRoute
  '/api/bbps/pay-bill': typeof ApiBbpsPayBillRoute
  '/api/escrow/status': typeof ApiEscrowStatusRoute
  '/api/loans/apply': typeof ApiLoansApplyRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/security/device-integrity': typeof ApiSecurityDeviceIntegrityRoute
  '/api/security/device-posture': typeof ApiSecurityDevicePostureRoute
  '/api/orders/$orderId/stream': typeof ApiOrdersOrderIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/king-pay': typeof KingPayRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/offers': typeof OffersRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tutor': typeof TutorRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/app/founder-command': typeof AppFounderCommandRoute
  '/dev/brand': typeof DevBrandRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/r/$slug': typeof RSlugRoute
  '/tracking/$dispatchJobId': typeof TrackingDispatchJobIdRoute
  '/account': typeof AccountIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/test-connection': typeof ApiAdminTestConnectionRoute
  '/api/affiliate/click': typeof ApiAffiliateClickRoute
  '/api/affiliates/offers': typeof ApiAffiliatesOffersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bbps/fetch-bill': typeof ApiBbpsFetchBillRoute
  '/api/bbps/pay-bill': typeof ApiBbpsPayBillRoute
  '/api/escrow/status': typeof ApiEscrowStatusRoute
  '/api/loans/apply': typeof ApiLoansApplyRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/security/device-integrity': typeof ApiSecurityDeviceIntegrityRoute
  '/api/security/device-posture': typeof ApiSecurityDevicePostureRoute
  '/api/orders/$orderId/stream': typeof ApiOrdersOrderIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/king-pay': typeof KingPayRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/offers': typeof OffersRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tutor': typeof TutorRoute
  '/api/referrals': typeof ApiReferralsRoute
  '/app/founder-command': typeof AppFounderCommandRoute
  '/dev/brand': typeof DevBrandRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/r/$slug': typeof RSlugRoute
  '/tracking/$dispatchJobId': typeof TrackingDispatchJobIdRoute
  '/account/': typeof AccountIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/test-connection': typeof ApiAdminTestConnectionRoute
  '/api/affiliate/click': typeof ApiAffiliateClickRoute
  '/api/affiliates/offers': typeof ApiAffiliatesOffersRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bbps/fetch-bill': typeof ApiBbpsFetchBillRoute
  '/api/bbps/pay-bill': typeof ApiBbpsPayBillRoute
  '/api/escrow/status': typeof ApiEscrowStatusRoute
  '/api/loans/apply': typeof ApiLoansApplyRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
  '/api/security/device-integrity': typeof ApiSecurityDeviceIntegrityRoute
  '/api/security/device-posture': typeof ApiSecurityDevicePostureRoute
  '/api/orders/$orderId/stream': typeof ApiOrdersOrderIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/king-pay'
    | '/login'
    | '/news'
    | '/offers'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/support'
    | '/tutor'
    | '/api/referrals'
    | '/app/founder-command'
    | '/dev/brand'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/orders/$id'
    | '/r/$slug'
    | '/tracking/$dispatchJobId'
    | '/account/'
    | '/orders/'
    | '/api/admin/settings'
    | '/api/admin/test-connection'
    | '/api/affiliate/click'
    | '/api/affiliates/offers'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/bbps/fetch-bill'
    | '/api/bbps/pay-bill'
    | '/api/escrow/status'
    | '/api/loans/apply'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
    | '/api/security/device-integrity'
    | '/api/security/device-posture'
    | '/api/orders/$orderId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/king-pay'
    | '/login'
    | '/news'
    | '/offers'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/support'
    | '/tutor'
    | '/api/referrals'
    | '/app/founder-command'
    | '/dev/brand'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/orders/$id'
    | '/r/$slug'
    | '/tracking/$dispatchJobId'
    | '/account'
    | '/orders'
    | '/api/admin/settings'
    | '/api/admin/test-connection'
    | '/api/affiliate/click'
    | '/api/affiliates/offers'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/bbps/fetch-bill'
    | '/api/bbps/pay-bill'
    | '/api/escrow/status'
    | '/api/loans/apply'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
    | '/api/security/device-integrity'
    | '/api/security/device-posture'
    | '/api/orders/$orderId/stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/king-pay'
    | '/login'
    | '/news'
    | '/offers'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/support'
    | '/tutor'
    | '/api/referrals'
    | '/app/founder-command'
    | '/dev/brand'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/orders/$id'
    | '/r/$slug'
    | '/tracking/$dispatchJobId'
    | '/account/'
    | '/orders/'
    | '/api/admin/settings'
    | '/api/admin/test-connection'
    | '/api/affiliate/click'
    | '/api/affiliates/offers'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/bbps/fetch-bill'
    | '/api/bbps/pay-bill'
    | '/api/escrow/status'
    | '/api/loans/apply'
    | '/api/razorpay/create-order'
    | '/api/razorpay/verify'
    | '/api/security/device-integrity'
    | '/api/security/device-posture'
    | '/api/orders/$orderId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  KingPayRoute: typeof KingPayRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  OffersRoute: typeof OffersRoute
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TutorRoute: typeof TutorRoute
  ApiReferralsRoute: typeof ApiReferralsRoute
  AppFounderCommandRoute: typeof AppFounderCommandRoute
  DevBrandRoute: typeof DevBrandRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RSlugRoute: typeof RSlugRoute
  TrackingDispatchJobIdRoute: typeof TrackingDispatchJobIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminTestConnectionRoute: typeof ApiAdminTestConnectionRoute
  ApiAffiliateClickRoute: typeof ApiAffiliateClickRoute
  ApiAffiliatesOffersRoute: typeof ApiAffiliatesOffersRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBbpsFetchBillRoute: typeof ApiBbpsFetchBillRoute
  ApiBbpsPayBillRoute: typeof ApiBbpsPayBillRoute
  ApiEscrowStatusRoute: typeof ApiEscrowStatusRoute
  ApiLoansApplyRoute: typeof ApiLoansApplyRoute
  ApiRazorpayCreateOrderRoute: typeof ApiRazorpayCreateOrderRoute
  ApiRazorpayVerifyRoute: typeof ApiRazorpayVerifyRoute
  ApiSecurityDeviceIntegrityRoute: typeof ApiSecurityDeviceIntegrityRoute
  ApiSecurityDevicePostureRoute: typeof ApiSecurityDevicePostureRoute
  ApiOrdersOrderIdStreamRoute: typeof ApiOrdersOrderIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/king-pay': {
      id: '/king-pay'
      path: '/king-pay'
      fullPath: '/king-pay'
      preLoaderRoute: typeof KingPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$dispatchJobId': {
      id: '/tracking/$dispatchJobId'
      path: '/tracking/$dispatchJobId'
      fullPath: '/tracking/$dispatchJobId'
      preLoaderRoute: typeof TrackingDispatchJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/brand': {
      id: '/dev/brand'
      path: '/dev/brand'
      fullPath: '/dev/brand'
      preLoaderRoute: typeof DevBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/founder-command': {
      id: '/app/founder-command'
      path: '/app/founder-command'
      fullPath: '/app/founder-command'
      preLoaderRoute: typeof AppFounderCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals': {
      id: '/api/referrals'
      path: '/api/referrals'
      fullPath: '/api/referrals'
      preLoaderRoute: typeof ApiReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/device-posture': {
      id: '/api/security/device-posture'
      path: '/api/security/device-posture'
      fullPath: '/api/security/device-posture'
      preLoaderRoute: typeof ApiSecurityDevicePostureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/security/device-integrity': {
      id: '/api/security/device-integrity'
      path: '/api/security/device-integrity'
      fullPath: '/api/security/device-integrity'
      preLoaderRoute: typeof ApiSecurityDeviceIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/verify': {
      id: '/api/razorpay/verify'
      path: '/api/razorpay/verify'
      fullPath: '/api/razorpay/verify'
      preLoaderRoute: typeof ApiRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/create-order': {
      id: '/api/razorpay/create-order'
      path: '/api/razorpay/create-order'
      fullPath: '/api/razorpay/create-order'
      preLoaderRoute: typeof ApiRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loans/apply': {
      id: '/api/loans/apply'
      path: '/api/loans/apply'
      fullPath: '/api/loans/apply'
      preLoaderRoute: typeof ApiLoansApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/escrow/status': {
      id: '/api/escrow/status'
      path: '/api/escrow/status'
      fullPath: '/api/escrow/status'
      preLoaderRoute: typeof ApiEscrowStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bbps/pay-bill': {
      id: '/api/bbps/pay-bill'
      path: '/api/bbps/pay-bill'
      fullPath: '/api/bbps/pay-bill'
      preLoaderRoute: typeof ApiBbpsPayBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bbps/fetch-bill': {
      id: '/api/bbps/fetch-bill'
      path: '/api/bbps/fetch-bill'
      fullPath: '/api/bbps/fetch-bill'
      preLoaderRoute: typeof ApiBbpsFetchBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliates/offers': {
      id: '/api/affiliates/offers'
      path: '/api/affiliates/offers'
      fullPath: '/api/affiliates/offers'
      preLoaderRoute: typeof ApiAffiliatesOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate/click': {
      id: '/api/affiliate/click'
      path: '/api/affiliate/click'
      fullPath: '/api/affiliate/click'
      preLoaderRoute: typeof ApiAffiliateClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/test-connection': {
      id: '/api/admin/test-connection'
      path: '/api/admin/test-connection'
      fullPath: '/api/admin/test-connection'
      preLoaderRoute: typeof ApiAdminTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/stream': {
      id: '/api/orders/$orderId/stream'
      path: '/api/orders/$orderId/stream'
      fullPath: '/api/orders/$orderId/stream'
      preLoaderRoute: typeof ApiOrdersOrderIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  KingPayRoute: KingPayRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  OffersRoute: OffersRoute,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TutorRoute: TutorRoute,
  ApiReferralsRoute: ApiReferralsRoute,
  AppFounderCommandRoute: AppFounderCommandRoute,
  DevBrandRoute: DevBrandRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  OrdersIdRoute: OrdersIdRoute,
  RSlugRoute: RSlugRoute,
  TrackingDispatchJobIdRoute: TrackingDispatchJobIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminTestConnectionRoute: ApiAdminTestConnectionRoute,
  ApiAffiliateClickRoute: ApiAffiliateClickRoute,
  ApiAffiliatesOffersRoute: ApiAffiliatesOffersRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBbpsFetchBillRoute: ApiBbpsFetchBillRoute,
  ApiBbpsPayBillRoute: ApiBbpsPayBillRoute,
  ApiEscrowStatusRoute: ApiEscrowStatusRoute,
  ApiLoansApplyRoute: ApiLoansApplyRoute,
  ApiRazorpayCreateOrderRoute: ApiRazorpayCreateOrderRoute,
  ApiRazorpayVerifyRoute: ApiRazorpayVerifyRoute,
  ApiSecurityDeviceIntegrityRoute: ApiSecurityDeviceIntegrityRoute,
  ApiSecurityDevicePostureRoute: ApiSecurityDevicePostureRoute,
  ApiOrdersOrderIdStreamRoute: ApiOrdersOrderIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
