/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as KingPayRouteImport } from './routes/king-pay'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AppFounderCommandRouteImport } from './routes/app/founder-command'
import { Route as DevBrandRouteImport } from './routes/dev/brand'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalRefundsRouteImport } from './routes/legal/refunds'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminTestConnectionRouteImport } from './routes/api/admin/test-connection'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOrdersOrderIdStreamRouteImport } from './routes/api/orders/$orderId/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const KingPayRoute = KingPayRouteImport.update({
  id: '/king-pay',
  path: '/king-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFounderCommandRoute = AppFounderCommandRouteImport.update({
  id: '/app/founder-command',
  path: '/app/founder-command',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBrandRoute = DevBrandRouteImport.update({
  id: '/dev/brand',
  path: '/dev/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestConnectionRoute = ApiAdminTestConnectionRouteImport.update({
  id: '/api/admin/test-connection',
  path: '/api/admin/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersOrderIdStreamRoute = ApiOrdersOrderIdStreamRouteImport.update({
  id: '/api/orders/$orderId/stream',
  path: '/api/orders/$orderId/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/king-pay': typeof KingPayRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/app/founder-command': typeof AppFounderCommandRoute
  '/dev/brand': typeof DevBrandRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/r/$slug': typeof RSlugRoute
  '/account/': typeof AccountIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/test-connection': typeof ApiAdminTestConnectionRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orders/$orderId/stream': typeof ApiOrdersOrderIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/king-pay': typeof KingPayRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/app/founder-command': typeof AppFounderCommandRoute
  '/dev/brand': typeof DevBrandRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/r/$slug': typeof RSlugRoute
  '/account': typeof AccountIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/test-connection': typeof ApiAdminTestConnectionRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orders/$orderId/stream': typeof ApiOrdersOrderIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/king-pay': typeof KingPayRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/rewards': typeof RewardsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/app/founder-command': typeof AppFounderCommandRoute
  '/dev/brand': typeof DevBrandRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/r/$slug': typeof RSlugRoute
  '/account/': typeof AccountIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/test-connection': typeof ApiAdminTestConnectionRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/orders/$orderId/stream': typeof ApiOrdersOrderIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/king-pay'
    | '/login'
    | '/offers'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/support'
    | '/app/founder-command'
    | '/dev/brand'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/orders/$id'
    | '/r/$slug'
    | '/account/'
    | '/orders/'
    | '/api/admin/settings'
    | '/api/admin/test-connection'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/orders/$orderId/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/king-pay'
    | '/login'
    | '/offers'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/support'
    | '/app/founder-command'
    | '/dev/brand'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/orders/$id'
    | '/r/$slug'
    | '/account'
    | '/orders'
    | '/api/admin/settings'
    | '/api/admin/test-connection'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/orders/$orderId/stream'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/king-pay'
    | '/login'
    | '/offers'
    | '/rewards'
    | '/search'
    | '/settings'
    | '/support'
    | '/app/founder-command'
    | '/dev/brand'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/orders/$id'
    | '/r/$slug'
    | '/account/'
    | '/orders/'
    | '/api/admin/settings'
    | '/api/admin/test-connection'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/orders/$orderId/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  KingPayRoute: typeof KingPayRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  RewardsRoute: typeof RewardsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  AppFounderCommandRoute: typeof AppFounderCommandRoute
  DevBrandRoute: typeof DevBrandRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RSlugRoute: typeof RSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminTestConnectionRoute: typeof ApiAdminTestConnectionRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrdersOrderIdStreamRoute: typeof ApiOrdersOrderIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/king-pay': {
      id: '/king-pay'
      path: '/king-pay'
      fullPath: '/king-pay'
      preLoaderRoute: typeof KingPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/founder-command': {
      id: '/app/founder-command'
      path: '/app/founder-command'
      fullPath: '/app/founder-command'
      preLoaderRoute: typeof AppFounderCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/brand': {
      id: '/dev/brand'
      path: '/dev/brand'
      fullPath: '/dev/brand'
      preLoaderRoute: typeof DevBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/test-connection': {
      id: '/api/admin/test-connection'
      path: '/api/admin/test-connection'
      fullPath: '/api/admin/test-connection'
      preLoaderRoute: typeof ApiAdminTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$orderId/stream': {
      id: '/api/orders/$orderId/stream'
      path: '/api/orders/$orderId/stream'
      fullPath: '/api/orders/$orderId/stream'
      preLoaderRoute: typeof ApiOrdersOrderIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  KingPayRoute: KingPayRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  RewardsRoute: RewardsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  AppFounderCommandRoute: AppFounderCommandRoute,
  DevBrandRoute: DevBrandRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  OrdersIdRoute: OrdersIdRoute,
  RSlugRoute: RSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminTestConnectionRoute: ApiAdminTestConnectionRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrdersOrderIdStreamRoute: ApiOrdersOrderIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
