/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppCeoRouteImport } from './routes/_app/ceo'
import { Route as AppCommerceRouteImport } from './routes/_app/commerce'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppDispatchRouteImport } from './routes/_app/dispatch'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppKycRouteImport } from './routes/_app/kyc'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppRestaurantsRouteImport } from './routes/_app/restaurants'
import { Route as AppRidersRouteImport } from './routes/_app/riders'
import { Route as AppRiskRouteImport } from './routes/_app/risk'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSecurityRouteImport } from './routes/_app/security'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCeoRoute = AppCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AppRoute,
} as any)
const AppCommerceRoute = AppCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDispatchRoute = AppDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppRestaurantsRoute = AppRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AppRoute,
} as any)
const AppRidersRoute = AppRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSecurityRoute = AppSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/ceo': typeof AppCeoRoute
  '/commerce': typeof AppCommerceRoute
  '/customers': typeof AppCustomersRoute
  '/dispatch': typeof AppDispatchRoute
  '/finance': typeof AppFinanceRoute
  '/kyc': typeof AppKycRoute
  '/map': typeof AppMapRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/people': typeof AppPeopleRoute
  '/restaurants': typeof AppRestaurantsRoute
  '/riders': typeof AppRidersRoute
  '/risk': typeof AppRiskRoute
  '/search': typeof AppSearchRoute
  '/security': typeof AppSecurityRoute
  '/support': typeof AppSupportRoute
  '/system': typeof AppSystemRoute
  '/tasks': typeof AppTasksRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/ceo': typeof AppCeoRoute
  '/commerce': typeof AppCommerceRoute
  '/customers': typeof AppCustomersRoute
  '/dispatch': typeof AppDispatchRoute
  '/finance': typeof AppFinanceRoute
  '/kyc': typeof AppKycRoute
  '/map': typeof AppMapRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRoute
  '/people': typeof AppPeopleRoute
  '/restaurants': typeof AppRestaurantsRoute
  '/riders': typeof AppRidersRoute
  '/risk': typeof AppRiskRoute
  '/search': typeof AppSearchRoute
  '/security': typeof AppSecurityRoute
  '/support': typeof AppSupportRoute
  '/system': typeof AppSystemRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/ceo': typeof AppCeoRoute
  '/_app/commerce': typeof AppCommerceRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dispatch': typeof AppDispatchRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/kyc': typeof AppKycRoute
  '/_app/map': typeof AppMapRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/restaurants': typeof AppRestaurantsRoute
  '/_app/riders': typeof AppRidersRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/security': typeof AppSecurityRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai'
    | '/analytics'
    | '/audit'
    | '/ceo'
    | '/commerce'
    | '/customers'
    | '/dispatch'
    | '/finance'
    | '/kyc'
    | '/map'
    | '/notifications'
    | '/orders'
    | '/people'
    | '/restaurants'
    | '/riders'
    | '/risk'
    | '/search'
    | '/security'
    | '/support'
    | '/system'
    | '/tasks'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ai'
    | '/analytics'
    | '/audit'
    | '/ceo'
    | '/commerce'
    | '/customers'
    | '/dispatch'
    | '/finance'
    | '/kyc'
    | '/map'
    | '/notifications'
    | '/orders'
    | '/people'
    | '/restaurants'
    | '/riders'
    | '/risk'
    | '/search'
    | '/security'
    | '/support'
    | '/system'
    | '/tasks'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/ai'
    | '/_app/analytics'
    | '/_app/audit'
    | '/_app/ceo'
    | '/_app/commerce'
    | '/_app/customers'
    | '/_app/dispatch'
    | '/_app/finance'
    | '/_app/kyc'
    | '/_app/map'
    | '/_app/notifications'
    | '/_app/orders'
    | '/_app/people'
    | '/_app/restaurants'
    | '/_app/riders'
    | '/_app/risk'
    | '/_app/search'
    | '/_app/security'
    | '/_app/support'
    | '/_app/system'
    | '/_app/tasks'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ceo': {
      id: '/_app/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AppCeoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commerce': {
      id: '/_app/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof AppCommerceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dispatch': {
      id: '/_app/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AppDispatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kyc': {
      id: '/_app/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restaurants': {
      id: '/_app/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof AppRestaurantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riders': {
      id: '/_app/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof AppRidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/security': {
      id: '/_app/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AppSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCeoRoute: typeof AppCeoRoute
  AppCommerceRoute: typeof AppCommerceRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDispatchRoute: typeof AppDispatchRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppKycRoute: typeof AppKycRoute
  AppMapRoute: typeof AppMapRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppRestaurantsRoute: typeof AppRestaurantsRoute
  AppRidersRoute: typeof AppRidersRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSecurityRoute: typeof AppSecurityRoute
  AppSupportRoute: typeof AppSupportRoute
  AppSystemRoute: typeof AppSystemRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCeoRoute: AppCeoRoute,
  AppCommerceRoute: AppCommerceRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDispatchRoute: AppDispatchRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppKycRoute: AppKycRoute,
  AppMapRoute: AppMapRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppRestaurantsRoute: AppRestaurantsRoute,
  AppRidersRoute: AppRidersRoute,
  AppRiskRoute: AppRiskRoute,
  AppSearchRoute: AppSearchRoute,
  AppSecurityRoute: AppSecurityRoute,
  AppSupportRoute: AppSupportRoute,
  AppSystemRoute: AppSystemRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
