/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppModuleRouteImport } from './routes/app/$module'
import { Route as ApiZomatoKillerCronRouteImport } from './routes/api/zomato-killer-cron'
import { Route as ApiTestOpenaiRouteImport } from './routes/api/test-openai'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as V1TravelSplatRouteImport } from './routes/v1/travel/$'
import { Route as V1PaymentsSplatRouteImport } from './routes/v1/payments/$'
import { Route as V1AdminSettlementEscalationsRouteImport } from './routes/v1/admin/settlement-escalations'
import { Route as V1AdminRiderOffersRouteImport } from './routes/v1/admin/rider-offers'
import { Route as V1AdminMasterAiRouteImport } from './routes/v1/admin/master-ai'
import { Route as V1AdminCustomerOrdersRouteImport } from './routes/v1/admin/customer-orders'
import { Route as V1AdminCustomerOrderRouteImport } from './routes/v1/admin/customer-order'
import { Route as V1AdminAffiliatesMetricsRouteImport } from './routes/v1/admin/affiliates-metrics'
import { Route as V1AdminSplatRouteImport } from './routes/v1/admin/$'
import { Route as AppModuleIdRouteImport } from './routes/app/$module.$id'
import { Route as ApiFinanceEscalationsRouteImport } from './routes/api/finance/escalations'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiTestConnectionRouteImport } from './routes/api/ai/test-connection'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as V1AdminDispatchReassignRouteImport } from './routes/v1/admin/dispatch/reassign'
import { Route as V1AdminCustomerOrdersIdRouteImport } from './routes/v1/admin/customer-orders/$id'
import { Route as V1AdminResourceIdRouteImport } from './routes/v1/admin/$resource.$id'
import { Route as ApiV1TravelSearchRouteImport } from './routes/api/v1/travel/search'
import { Route as ApiV1TravelBookRouteImport } from './routes/api/v1/travel/book'
import { Route as ApiV1KingpayTransferRouteImport } from './routes/api/v1/kingpay/transfer'
import { Route as ApiV1KingpayRazorpayWebhookRouteImport } from './routes/api/v1/kingpay/razorpay-webhook'
import { Route as ApiV1IntegrationsTravelRouteImport } from './routes/api/v1/integrations/travel'
import { Route as ApiV1IntegrationsOpenaiRouteImport } from './routes/api/v1/integrations/openai'
import { Route as ApiV1GrowthQualifyRouteImport } from './routes/api/v1/growth/qualify'
import { Route as ApiV1FounderSweepRouteImport } from './routes/api/v1/founder/sweep'
import { Route as ApiV1FounderPrNominationsRouteImport } from './routes/api/v1/founder/pr-nominations'
import { Route as ApiV1FounderJobsRouteImport } from './routes/api/v1/founder/jobs'
import { Route as ApiV1FinanceWeeklySettlementReportRouteImport } from './routes/api/v1/finance/weekly-settlement-report'
import { Route as ApiV1FinanceSubscriptionRouteImport } from './routes/api/v1/finance/subscription'
import { Route as ApiV1AdminAiProviderTestRouteImport } from './routes/api/v1/admin/ai-provider-test'
import { Route as ApiFinanceCronRunSettlementRouteImport } from './routes/api/finance/cron/run-settlement'
import { Route as ApiDispatchCronRunAutoDispatchRouteImport } from './routes/api/dispatch/cron/run-auto-dispatch'
import { Route as V1AdminOrdersIdRiderTransitionRouteImport } from './routes/v1/admin/orders/$id/rider-transition'
import { Route as V1AdminCustomerOrdersIdCancelRouteImport } from './routes/v1/admin/customer-orders/$id/cancel'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiZomatoKillerCronRoute = ApiZomatoKillerCronRouteImport.update({
  id: '/api/zomato-killer-cron',
  path: '/api/zomato-killer-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestOpenaiRoute = ApiTestOpenaiRouteImport.update({
  id: '/api/test-openai',
  path: '/api/test-openai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TravelSplatRoute = V1TravelSplatRouteImport.update({
  id: '/v1/travel/$',
  path: '/v1/travel/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PaymentsSplatRoute = V1PaymentsSplatRouteImport.update({
  id: '/v1/payments/$',
  path: '/v1/payments/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminSettlementEscalationsRoute =
  V1AdminSettlementEscalationsRouteImport.update({
    id: '/v1/admin/settlement-escalations',
    path: '/v1/admin/settlement-escalations',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1AdminRiderOffersRoute = V1AdminRiderOffersRouteImport.update({
  id: '/v1/admin/rider-offers',
  path: '/v1/admin/rider-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminMasterAiRoute = V1AdminMasterAiRouteImport.update({
  id: '/v1/admin/master-ai',
  path: '/v1/admin/master-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminCustomerOrdersRoute = V1AdminCustomerOrdersRouteImport.update({
  id: '/v1/admin/customer-orders',
  path: '/v1/admin/customer-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminCustomerOrderRoute = V1AdminCustomerOrderRouteImport.update({
  id: '/v1/admin/customer-order',
  path: '/v1/admin/customer-order',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminAffiliatesMetricsRoute =
  V1AdminAffiliatesMetricsRouteImport.update({
    id: '/v1/admin/affiliates-metrics',
    path: '/v1/admin/affiliates-metrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1AdminSplatRoute = V1AdminSplatRouteImport.update({
  id: '/v1/admin/$',
  path: '/v1/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModuleIdRoute = AppModuleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppModuleRoute,
} as any)
const ApiFinanceEscalationsRoute = ApiFinanceEscalationsRouteImport.update({
  id: '/api/finance/escalations',
  path: '/api/finance/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestConnectionRoute = ApiAiTestConnectionRouteImport.update({
  id: '/api/ai/test-connection',
  path: '/api/ai/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminDispatchReassignRoute = V1AdminDispatchReassignRouteImport.update({
  id: '/v1/admin/dispatch/reassign',
  path: '/v1/admin/dispatch/reassign',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminCustomerOrdersIdRoute = V1AdminCustomerOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => V1AdminCustomerOrdersRoute,
} as any)
const V1AdminResourceIdRoute = V1AdminResourceIdRouteImport.update({
  id: '/v1/admin/$resource/$id',
  path: '/v1/admin/$resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TravelSearchRoute = ApiV1TravelSearchRouteImport.update({
  id: '/api/v1/travel/search',
  path: '/api/v1/travel/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TravelBookRoute = ApiV1TravelBookRouteImport.update({
  id: '/api/v1/travel/book',
  path: '/api/v1/travel/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1KingpayTransferRoute = ApiV1KingpayTransferRouteImport.update({
  id: '/api/v1/kingpay/transfer',
  path: '/api/v1/kingpay/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1KingpayRazorpayWebhookRoute =
  ApiV1KingpayRazorpayWebhookRouteImport.update({
    id: '/api/v1/kingpay/razorpay-webhook',
    path: '/api/v1/kingpay/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1IntegrationsTravelRoute = ApiV1IntegrationsTravelRouteImport.update({
  id: '/api/v1/integrations/travel',
  path: '/api/v1/integrations/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IntegrationsOpenaiRoute = ApiV1IntegrationsOpenaiRouteImport.update({
  id: '/api/v1/integrations/openai',
  path: '/api/v1/integrations/openai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GrowthQualifyRoute = ApiV1GrowthQualifyRouteImport.update({
  id: '/api/v1/growth/qualify',
  path: '/api/v1/growth/qualify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FounderSweepRoute = ApiV1FounderSweepRouteImport.update({
  id: '/api/v1/founder/sweep',
  path: '/api/v1/founder/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FounderPrNominationsRoute =
  ApiV1FounderPrNominationsRouteImport.update({
    id: '/api/v1/founder/pr-nominations',
    path: '/api/v1/founder/pr-nominations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FounderJobsRoute = ApiV1FounderJobsRouteImport.update({
  id: '/api/v1/founder/jobs',
  path: '/api/v1/founder/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FinanceWeeklySettlementReportRoute =
  ApiV1FinanceWeeklySettlementReportRouteImport.update({
    id: '/api/v1/finance/weekly-settlement-report',
    path: '/api/v1/finance/weekly-settlement-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1FinanceSubscriptionRoute =
  ApiV1FinanceSubscriptionRouteImport.update({
    id: '/api/v1/finance/subscription',
    path: '/api/v1/finance/subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminAiProviderTestRoute =
  ApiV1AdminAiProviderTestRouteImport.update({
    id: '/api/v1/admin/ai-provider-test',
    path: '/api/v1/admin/ai-provider-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFinanceCronRunSettlementRoute =
  ApiFinanceCronRunSettlementRouteImport.update({
    id: '/api/finance/cron/run-settlement',
    path: '/api/finance/cron/run-settlement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDispatchCronRunAutoDispatchRoute =
  ApiDispatchCronRunAutoDispatchRouteImport.update({
    id: '/api/dispatch/cron/run-auto-dispatch',
    path: '/api/dispatch/cron/run-auto-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1AdminOrdersIdRiderTransitionRoute =
  V1AdminOrdersIdRiderTransitionRouteImport.update({
    id: '/v1/admin/orders/$id/rider-transition',
    path: '/v1/admin/orders/$id/rider-transition',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1AdminCustomerOrdersIdCancelRoute =
  V1AdminCustomerOrdersIdCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => V1AdminCustomerOrdersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/test-openai': typeof ApiTestOpenaiRoute
  '/api/zomato-killer-cron': typeof ApiZomatoKillerCronRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/finance/escalations': typeof ApiFinanceEscalationsRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/affiliates-metrics': typeof V1AdminAffiliatesMetricsRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRouteWithChildren
  '/v1/admin/master-ai': typeof V1AdminMasterAiRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/admin/settlement-escalations': typeof V1AdminSettlementEscalationsRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
  '/v1/travel/$': typeof V1TravelSplatRoute
  '/api/dispatch/cron/run-auto-dispatch': typeof ApiDispatchCronRunAutoDispatchRoute
  '/api/finance/cron/run-settlement': typeof ApiFinanceCronRunSettlementRoute
  '/api/v1/admin/ai-provider-test': typeof ApiV1AdminAiProviderTestRoute
  '/api/v1/finance/subscription': typeof ApiV1FinanceSubscriptionRoute
  '/api/v1/finance/weekly-settlement-report': typeof ApiV1FinanceWeeklySettlementReportRoute
  '/api/v1/founder/jobs': typeof ApiV1FounderJobsRoute
  '/api/v1/founder/pr-nominations': typeof ApiV1FounderPrNominationsRoute
  '/api/v1/founder/sweep': typeof ApiV1FounderSweepRoute
  '/api/v1/growth/qualify': typeof ApiV1GrowthQualifyRoute
  '/api/v1/integrations/openai': typeof ApiV1IntegrationsOpenaiRoute
  '/api/v1/integrations/travel': typeof ApiV1IntegrationsTravelRoute
  '/api/v1/kingpay/razorpay-webhook': typeof ApiV1KingpayRazorpayWebhookRoute
  '/api/v1/kingpay/transfer': typeof ApiV1KingpayTransferRoute
  '/api/v1/travel/book': typeof ApiV1TravelBookRoute
  '/api/v1/travel/search': typeof ApiV1TravelSearchRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/customer-orders/$id': typeof V1AdminCustomerOrdersIdRouteWithChildren
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-orders/$id/cancel': typeof V1AdminCustomerOrdersIdCancelRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/test-openai': typeof ApiTestOpenaiRoute
  '/api/zomato-killer-cron': typeof ApiZomatoKillerCronRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/finance/escalations': typeof ApiFinanceEscalationsRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/affiliates-metrics': typeof V1AdminAffiliatesMetricsRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRouteWithChildren
  '/v1/admin/master-ai': typeof V1AdminMasterAiRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/admin/settlement-escalations': typeof V1AdminSettlementEscalationsRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
  '/v1/travel/$': typeof V1TravelSplatRoute
  '/api/dispatch/cron/run-auto-dispatch': typeof ApiDispatchCronRunAutoDispatchRoute
  '/api/finance/cron/run-settlement': typeof ApiFinanceCronRunSettlementRoute
  '/api/v1/admin/ai-provider-test': typeof ApiV1AdminAiProviderTestRoute
  '/api/v1/finance/subscription': typeof ApiV1FinanceSubscriptionRoute
  '/api/v1/finance/weekly-settlement-report': typeof ApiV1FinanceWeeklySettlementReportRoute
  '/api/v1/founder/jobs': typeof ApiV1FounderJobsRoute
  '/api/v1/founder/pr-nominations': typeof ApiV1FounderPrNominationsRoute
  '/api/v1/founder/sweep': typeof ApiV1FounderSweepRoute
  '/api/v1/growth/qualify': typeof ApiV1GrowthQualifyRoute
  '/api/v1/integrations/openai': typeof ApiV1IntegrationsOpenaiRoute
  '/api/v1/integrations/travel': typeof ApiV1IntegrationsTravelRoute
  '/api/v1/kingpay/razorpay-webhook': typeof ApiV1KingpayRazorpayWebhookRoute
  '/api/v1/kingpay/transfer': typeof ApiV1KingpayTransferRoute
  '/api/v1/travel/book': typeof ApiV1TravelBookRoute
  '/api/v1/travel/search': typeof ApiV1TravelSearchRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/customer-orders/$id': typeof V1AdminCustomerOrdersIdRouteWithChildren
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-orders/$id/cancel': typeof V1AdminCustomerOrdersIdCancelRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/test-openai': typeof ApiTestOpenaiRoute
  '/api/zomato-killer-cron': typeof ApiZomatoKillerCronRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/finance/escalations': typeof ApiFinanceEscalationsRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/affiliates-metrics': typeof V1AdminAffiliatesMetricsRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRouteWithChildren
  '/v1/admin/master-ai': typeof V1AdminMasterAiRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/admin/settlement-escalations': typeof V1AdminSettlementEscalationsRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
  '/v1/travel/$': typeof V1TravelSplatRoute
  '/api/dispatch/cron/run-auto-dispatch': typeof ApiDispatchCronRunAutoDispatchRoute
  '/api/finance/cron/run-settlement': typeof ApiFinanceCronRunSettlementRoute
  '/api/v1/admin/ai-provider-test': typeof ApiV1AdminAiProviderTestRoute
  '/api/v1/finance/subscription': typeof ApiV1FinanceSubscriptionRoute
  '/api/v1/finance/weekly-settlement-report': typeof ApiV1FinanceWeeklySettlementReportRoute
  '/api/v1/founder/jobs': typeof ApiV1FounderJobsRoute
  '/api/v1/founder/pr-nominations': typeof ApiV1FounderPrNominationsRoute
  '/api/v1/founder/sweep': typeof ApiV1FounderSweepRoute
  '/api/v1/growth/qualify': typeof ApiV1GrowthQualifyRoute
  '/api/v1/integrations/openai': typeof ApiV1IntegrationsOpenaiRoute
  '/api/v1/integrations/travel': typeof ApiV1IntegrationsTravelRoute
  '/api/v1/kingpay/razorpay-webhook': typeof ApiV1KingpayRazorpayWebhookRoute
  '/api/v1/kingpay/transfer': typeof ApiV1KingpayTransferRoute
  '/api/v1/travel/book': typeof ApiV1TravelBookRoute
  '/api/v1/travel/search': typeof ApiV1TravelSearchRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/customer-orders/$id': typeof V1AdminCustomerOrdersIdRouteWithChildren
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-orders/$id/cancel': typeof V1AdminCustomerOrdersIdCancelRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/api/telemetry'
    | '/api/test-openai'
    | '/api/zomato-killer-cron'
    | '/app/$module'
    | '/app/'
    | '/api/ai/chat'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/api/finance/escalations'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/affiliates-metrics'
    | '/v1/admin/customer-order'
    | '/v1/admin/customer-orders'
    | '/v1/admin/master-ai'
    | '/v1/admin/rider-offers'
    | '/v1/admin/settlement-escalations'
    | '/v1/payments/$'
    | '/v1/travel/$'
    | '/api/dispatch/cron/run-auto-dispatch'
    | '/api/finance/cron/run-settlement'
    | '/api/v1/admin/ai-provider-test'
    | '/api/v1/finance/subscription'
    | '/api/v1/finance/weekly-settlement-report'
    | '/api/v1/founder/jobs'
    | '/api/v1/founder/pr-nominations'
    | '/api/v1/founder/sweep'
    | '/api/v1/growth/qualify'
    | '/api/v1/integrations/openai'
    | '/api/v1/integrations/travel'
    | '/api/v1/kingpay/razorpay-webhook'
    | '/api/v1/kingpay/transfer'
    | '/api/v1/travel/book'
    | '/api/v1/travel/search'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/customer-orders/$id'
    | '/v1/admin/dispatch/reassign'
    | '/v1/admin/customer-orders/$id/cancel'
    | '/v1/admin/orders/$id/rider-transition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/api/telemetry'
    | '/api/test-openai'
    | '/api/zomato-killer-cron'
    | '/app/$module'
    | '/app'
    | '/api/ai/chat'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/api/finance/escalations'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/affiliates-metrics'
    | '/v1/admin/customer-order'
    | '/v1/admin/customer-orders'
    | '/v1/admin/master-ai'
    | '/v1/admin/rider-offers'
    | '/v1/admin/settlement-escalations'
    | '/v1/payments/$'
    | '/v1/travel/$'
    | '/api/dispatch/cron/run-auto-dispatch'
    | '/api/finance/cron/run-settlement'
    | '/api/v1/admin/ai-provider-test'
    | '/api/v1/finance/subscription'
    | '/api/v1/finance/weekly-settlement-report'
    | '/api/v1/founder/jobs'
    | '/api/v1/founder/pr-nominations'
    | '/api/v1/founder/sweep'
    | '/api/v1/growth/qualify'
    | '/api/v1/integrations/openai'
    | '/api/v1/integrations/travel'
    | '/api/v1/kingpay/razorpay-webhook'
    | '/api/v1/kingpay/transfer'
    | '/api/v1/travel/book'
    | '/api/v1/travel/search'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/customer-orders/$id'
    | '/v1/admin/dispatch/reassign'
    | '/v1/admin/customer-orders/$id/cancel'
    | '/v1/admin/orders/$id/rider-transition'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/health'
    | '/api/telemetry'
    | '/api/test-openai'
    | '/api/zomato-killer-cron'
    | '/app/$module'
    | '/app/'
    | '/api/ai/chat'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/api/finance/escalations'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/affiliates-metrics'
    | '/v1/admin/customer-order'
    | '/v1/admin/customer-orders'
    | '/v1/admin/master-ai'
    | '/v1/admin/rider-offers'
    | '/v1/admin/settlement-escalations'
    | '/v1/payments/$'
    | '/v1/travel/$'
    | '/api/dispatch/cron/run-auto-dispatch'
    | '/api/finance/cron/run-settlement'
    | '/api/v1/admin/ai-provider-test'
    | '/api/v1/finance/subscription'
    | '/api/v1/finance/weekly-settlement-report'
    | '/api/v1/founder/jobs'
    | '/api/v1/founder/pr-nominations'
    | '/api/v1/founder/sweep'
    | '/api/v1/growth/qualify'
    | '/api/v1/integrations/openai'
    | '/api/v1/integrations/travel'
    | '/api/v1/kingpay/razorpay-webhook'
    | '/api/v1/kingpay/transfer'
    | '/api/v1/travel/book'
    | '/api/v1/travel/search'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/customer-orders/$id'
    | '/v1/admin/dispatch/reassign'
    | '/v1/admin/customer-orders/$id/cancel'
    | '/v1/admin/orders/$id/rider-transition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  ApiTestOpenaiRoute: typeof ApiTestOpenaiRoute
  ApiZomatoKillerCronRoute: typeof ApiZomatoKillerCronRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiTestConnectionRoute: typeof ApiAiTestConnectionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFinanceEscalationsRoute: typeof ApiFinanceEscalationsRoute
  V1AdminSplatRoute: typeof V1AdminSplatRoute
  V1AdminAffiliatesMetricsRoute: typeof V1AdminAffiliatesMetricsRoute
  V1AdminCustomerOrderRoute: typeof V1AdminCustomerOrderRoute
  V1AdminCustomerOrdersRoute: typeof V1AdminCustomerOrdersRouteWithChildren
  V1AdminMasterAiRoute: typeof V1AdminMasterAiRoute
  V1AdminRiderOffersRoute: typeof V1AdminRiderOffersRoute
  V1AdminSettlementEscalationsRoute: typeof V1AdminSettlementEscalationsRoute
  V1PaymentsSplatRoute: typeof V1PaymentsSplatRoute
  V1TravelSplatRoute: typeof V1TravelSplatRoute
  ApiDispatchCronRunAutoDispatchRoute: typeof ApiDispatchCronRunAutoDispatchRoute
  ApiFinanceCronRunSettlementRoute: typeof ApiFinanceCronRunSettlementRoute
  ApiV1AdminAiProviderTestRoute: typeof ApiV1AdminAiProviderTestRoute
  ApiV1FinanceSubscriptionRoute: typeof ApiV1FinanceSubscriptionRoute
  ApiV1FinanceWeeklySettlementReportRoute: typeof ApiV1FinanceWeeklySettlementReportRoute
  ApiV1FounderJobsRoute: typeof ApiV1FounderJobsRoute
  ApiV1FounderPrNominationsRoute: typeof ApiV1FounderPrNominationsRoute
  ApiV1FounderSweepRoute: typeof ApiV1FounderSweepRoute
  ApiV1GrowthQualifyRoute: typeof ApiV1GrowthQualifyRoute
  ApiV1IntegrationsOpenaiRoute: typeof ApiV1IntegrationsOpenaiRoute
  ApiV1IntegrationsTravelRoute: typeof ApiV1IntegrationsTravelRoute
  ApiV1KingpayRazorpayWebhookRoute: typeof ApiV1KingpayRazorpayWebhookRoute
  ApiV1KingpayTransferRoute: typeof ApiV1KingpayTransferRoute
  ApiV1TravelBookRoute: typeof ApiV1TravelBookRoute
  ApiV1TravelSearchRoute: typeof ApiV1TravelSearchRoute
  V1AdminResourceIdRoute: typeof V1AdminResourceIdRoute
  V1AdminDispatchReassignRoute: typeof V1AdminDispatchReassignRoute
  V1AdminOrdersIdRiderTransitionRoute: typeof V1AdminOrdersIdRiderTransitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/zomato-killer-cron': {
      id: '/api/zomato-killer-cron'
      path: '/api/zomato-killer-cron'
      fullPath: '/api/zomato-killer-cron'
      preLoaderRoute: typeof ApiZomatoKillerCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-openai': {
      id: '/api/test-openai'
      path: '/api/test-openai'
      fullPath: '/api/test-openai'
      preLoaderRoute: typeof ApiTestOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/travel/$': {
      id: '/v1/travel/$'
      path: '/v1/travel/$'
      fullPath: '/v1/travel/$'
      preLoaderRoute: typeof V1TravelSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/payments/$': {
      id: '/v1/payments/$'
      path: '/v1/payments/$'
      fullPath: '/v1/payments/$'
      preLoaderRoute: typeof V1PaymentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/settlement-escalations': {
      id: '/v1/admin/settlement-escalations'
      path: '/v1/admin/settlement-escalations'
      fullPath: '/v1/admin/settlement-escalations'
      preLoaderRoute: typeof V1AdminSettlementEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/rider-offers': {
      id: '/v1/admin/rider-offers'
      path: '/v1/admin/rider-offers'
      fullPath: '/v1/admin/rider-offers'
      preLoaderRoute: typeof V1AdminRiderOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/master-ai': {
      id: '/v1/admin/master-ai'
      path: '/v1/admin/master-ai'
      fullPath: '/v1/admin/master-ai'
      preLoaderRoute: typeof V1AdminMasterAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-orders': {
      id: '/v1/admin/customer-orders'
      path: '/v1/admin/customer-orders'
      fullPath: '/v1/admin/customer-orders'
      preLoaderRoute: typeof V1AdminCustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-order': {
      id: '/v1/admin/customer-order'
      path: '/v1/admin/customer-order'
      fullPath: '/v1/admin/customer-order'
      preLoaderRoute: typeof V1AdminCustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/affiliates-metrics': {
      id: '/v1/admin/affiliates-metrics'
      path: '/v1/admin/affiliates-metrics'
      fullPath: '/v1/admin/affiliates-metrics'
      preLoaderRoute: typeof V1AdminAffiliatesMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/$': {
      id: '/v1/admin/$'
      path: '/v1/admin/$'
      fullPath: '/v1/admin/$'
      preLoaderRoute: typeof V1AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$module/$id': {
      id: '/app/$module/$id'
      path: '/$id'
      fullPath: '/app/$module/$id'
      preLoaderRoute: typeof AppModuleIdRouteImport
      parentRoute: typeof AppModuleRoute
    }
    '/api/finance/escalations': {
      id: '/api/finance/escalations'
      path: '/api/finance/escalations'
      fullPath: '/api/finance/escalations'
      preLoaderRoute: typeof ApiFinanceEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/test-connection': {
      id: '/api/ai/test-connection'
      path: '/api/ai/test-connection'
      fullPath: '/api/ai/test-connection'
      preLoaderRoute: typeof ApiAiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/dispatch/reassign': {
      id: '/v1/admin/dispatch/reassign'
      path: '/v1/admin/dispatch/reassign'
      fullPath: '/v1/admin/dispatch/reassign'
      preLoaderRoute: typeof V1AdminDispatchReassignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-orders/$id': {
      id: '/v1/admin/customer-orders/$id'
      path: '/$id'
      fullPath: '/v1/admin/customer-orders/$id'
      preLoaderRoute: typeof V1AdminCustomerOrdersIdRouteImport
      parentRoute: typeof V1AdminCustomerOrdersRoute
    }
    '/v1/admin/$resource/$id': {
      id: '/v1/admin/$resource/$id'
      path: '/v1/admin/$resource/$id'
      fullPath: '/v1/admin/$resource/$id'
      preLoaderRoute: typeof V1AdminResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/travel/search': {
      id: '/api/v1/travel/search'
      path: '/api/v1/travel/search'
      fullPath: '/api/v1/travel/search'
      preLoaderRoute: typeof ApiV1TravelSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/travel/book': {
      id: '/api/v1/travel/book'
      path: '/api/v1/travel/book'
      fullPath: '/api/v1/travel/book'
      preLoaderRoute: typeof ApiV1TravelBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/kingpay/transfer': {
      id: '/api/v1/kingpay/transfer'
      path: '/api/v1/kingpay/transfer'
      fullPath: '/api/v1/kingpay/transfer'
      preLoaderRoute: typeof ApiV1KingpayTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/kingpay/razorpay-webhook': {
      id: '/api/v1/kingpay/razorpay-webhook'
      path: '/api/v1/kingpay/razorpay-webhook'
      fullPath: '/api/v1/kingpay/razorpay-webhook'
      preLoaderRoute: typeof ApiV1KingpayRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/integrations/travel': {
      id: '/api/v1/integrations/travel'
      path: '/api/v1/integrations/travel'
      fullPath: '/api/v1/integrations/travel'
      preLoaderRoute: typeof ApiV1IntegrationsTravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/integrations/openai': {
      id: '/api/v1/integrations/openai'
      path: '/api/v1/integrations/openai'
      fullPath: '/api/v1/integrations/openai'
      preLoaderRoute: typeof ApiV1IntegrationsOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/growth/qualify': {
      id: '/api/v1/growth/qualify'
      path: '/api/v1/growth/qualify'
      fullPath: '/api/v1/growth/qualify'
      preLoaderRoute: typeof ApiV1GrowthQualifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/founder/sweep': {
      id: '/api/v1/founder/sweep'
      path: '/api/v1/founder/sweep'
      fullPath: '/api/v1/founder/sweep'
      preLoaderRoute: typeof ApiV1FounderSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/founder/pr-nominations': {
      id: '/api/v1/founder/pr-nominations'
      path: '/api/v1/founder/pr-nominations'
      fullPath: '/api/v1/founder/pr-nominations'
      preLoaderRoute: typeof ApiV1FounderPrNominationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/founder/jobs': {
      id: '/api/v1/founder/jobs'
      path: '/api/v1/founder/jobs'
      fullPath: '/api/v1/founder/jobs'
      preLoaderRoute: typeof ApiV1FounderJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/finance/weekly-settlement-report': {
      id: '/api/v1/finance/weekly-settlement-report'
      path: '/api/v1/finance/weekly-settlement-report'
      fullPath: '/api/v1/finance/weekly-settlement-report'
      preLoaderRoute: typeof ApiV1FinanceWeeklySettlementReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/finance/subscription': {
      id: '/api/v1/finance/subscription'
      path: '/api/v1/finance/subscription'
      fullPath: '/api/v1/finance/subscription'
      preLoaderRoute: typeof ApiV1FinanceSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/ai-provider-test': {
      id: '/api/v1/admin/ai-provider-test'
      path: '/api/v1/admin/ai-provider-test'
      fullPath: '/api/v1/admin/ai-provider-test'
      preLoaderRoute: typeof ApiV1AdminAiProviderTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/cron/run-settlement': {
      id: '/api/finance/cron/run-settlement'
      path: '/api/finance/cron/run-settlement'
      fullPath: '/api/finance/cron/run-settlement'
      preLoaderRoute: typeof ApiFinanceCronRunSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dispatch/cron/run-auto-dispatch': {
      id: '/api/dispatch/cron/run-auto-dispatch'
      path: '/api/dispatch/cron/run-auto-dispatch'
      fullPath: '/api/dispatch/cron/run-auto-dispatch'
      preLoaderRoute: typeof ApiDispatchCronRunAutoDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/orders/$id/rider-transition': {
      id: '/v1/admin/orders/$id/rider-transition'
      path: '/v1/admin/orders/$id/rider-transition'
      fullPath: '/v1/admin/orders/$id/rider-transition'
      preLoaderRoute: typeof V1AdminOrdersIdRiderTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-orders/$id/cancel': {
      id: '/v1/admin/customer-orders/$id/cancel'
      path: '/cancel'
      fullPath: '/v1/admin/customer-orders/$id/cancel'
      preLoaderRoute: typeof V1AdminCustomerOrdersIdCancelRouteImport
      parentRoute: typeof V1AdminCustomerOrdersIdRoute
    }
  }
}

interface AppModuleRouteChildren {
  AppModuleIdRoute: typeof AppModuleIdRoute
}

const AppModuleRouteChildren: AppModuleRouteChildren = {
  AppModuleIdRoute: AppModuleIdRoute,
}

const AppModuleRouteWithChildren = AppModuleRoute._addFileChildren(
  AppModuleRouteChildren,
)

interface AppRouteRouteChildren {
  AppModuleRoute: typeof AppModuleRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppModuleRoute: AppModuleRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface V1AdminCustomerOrdersIdRouteChildren {
  V1AdminCustomerOrdersIdCancelRoute: typeof V1AdminCustomerOrdersIdCancelRoute
}

const V1AdminCustomerOrdersIdRouteChildren: V1AdminCustomerOrdersIdRouteChildren =
  {
    V1AdminCustomerOrdersIdCancelRoute: V1AdminCustomerOrdersIdCancelRoute,
  }

const V1AdminCustomerOrdersIdRouteWithChildren =
  V1AdminCustomerOrdersIdRoute._addFileChildren(
    V1AdminCustomerOrdersIdRouteChildren,
  )

interface V1AdminCustomerOrdersRouteChildren {
  V1AdminCustomerOrdersIdRoute: typeof V1AdminCustomerOrdersIdRouteWithChildren
}

const V1AdminCustomerOrdersRouteChildren: V1AdminCustomerOrdersRouteChildren = {
  V1AdminCustomerOrdersIdRoute: V1AdminCustomerOrdersIdRouteWithChildren,
}

const V1AdminCustomerOrdersRouteWithChildren =
  V1AdminCustomerOrdersRoute._addFileChildren(
    V1AdminCustomerOrdersRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  ApiTestOpenaiRoute: ApiTestOpenaiRoute,
  ApiZomatoKillerCronRoute: ApiZomatoKillerCronRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiTestConnectionRoute: ApiAiTestConnectionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFinanceEscalationsRoute: ApiFinanceEscalationsRoute,
  V1AdminSplatRoute: V1AdminSplatRoute,
  V1AdminAffiliatesMetricsRoute: V1AdminAffiliatesMetricsRoute,
  V1AdminCustomerOrderRoute: V1AdminCustomerOrderRoute,
  V1AdminCustomerOrdersRoute: V1AdminCustomerOrdersRouteWithChildren,
  V1AdminMasterAiRoute: V1AdminMasterAiRoute,
  V1AdminRiderOffersRoute: V1AdminRiderOffersRoute,
  V1AdminSettlementEscalationsRoute: V1AdminSettlementEscalationsRoute,
  V1PaymentsSplatRoute: V1PaymentsSplatRoute,
  V1TravelSplatRoute: V1TravelSplatRoute,
  ApiDispatchCronRunAutoDispatchRoute: ApiDispatchCronRunAutoDispatchRoute,
  ApiFinanceCronRunSettlementRoute: ApiFinanceCronRunSettlementRoute,
  ApiV1AdminAiProviderTestRoute: ApiV1AdminAiProviderTestRoute,
  ApiV1FinanceSubscriptionRoute: ApiV1FinanceSubscriptionRoute,
  ApiV1FinanceWeeklySettlementReportRoute:
    ApiV1FinanceWeeklySettlementReportRoute,
  ApiV1FounderJobsRoute: ApiV1FounderJobsRoute,
  ApiV1FounderPrNominationsRoute: ApiV1FounderPrNominationsRoute,
  ApiV1FounderSweepRoute: ApiV1FounderSweepRoute,
  ApiV1GrowthQualifyRoute: ApiV1GrowthQualifyRoute,
  ApiV1IntegrationsOpenaiRoute: ApiV1IntegrationsOpenaiRoute,
  ApiV1IntegrationsTravelRoute: ApiV1IntegrationsTravelRoute,
  ApiV1KingpayRazorpayWebhookRoute: ApiV1KingpayRazorpayWebhookRoute,
  ApiV1KingpayTransferRoute: ApiV1KingpayTransferRoute,
  ApiV1TravelBookRoute: ApiV1TravelBookRoute,
  ApiV1TravelSearchRoute: ApiV1TravelSearchRoute,
  V1AdminResourceIdRoute: V1AdminResourceIdRoute,
  V1AdminDispatchReassignRoute: V1AdminDispatchReassignRoute,
  V1AdminOrdersIdRiderTransitionRoute: V1AdminOrdersIdRiderTransitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
