/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiTestOpenaiRouteImport } from './routes/api/test-openai'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppModuleRouteImport } from './routes/app/$module'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiTestConnectionRouteImport } from './routes/api/ai/test-connection'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppModuleIdRouteImport } from './routes/app/$module.$id'
import { Route as V1AdminSplatRouteImport } from './routes/v1/admin/$'
import { Route as V1AdminCustomerOrderRouteImport } from './routes/v1/admin/customer-order'
import { Route as V1AdminCustomerOrdersRouteImport } from './routes/v1/admin/customer-orders'
import { Route as V1AdminMasterAiRouteImport } from './routes/v1/admin/master-ai'
import { Route as V1AdminRiderOffersRouteImport } from './routes/v1/admin/rider-offers'
import { Route as V1PaymentsSplatRouteImport } from './routes/v1/payments/$'
import { Route as V1TravelSplatRouteImport } from './routes/v1/travel/$'
import { Route as V1AdminResourceIdRouteImport } from './routes/v1/admin/$resource.$id'
import { Route as V1AdminCustomerOrdersIdRouteImport } from './routes/v1/admin/customer-orders/$id'
import { Route as V1AdminDispatchReassignRouteImport } from './routes/v1/admin/dispatch/reassign'
import { Route as V1AdminCustomerOrdersIdCancelRouteImport } from './routes/v1/admin/customer-orders/$id/cancel'
import { Route as V1AdminOrdersIdRiderTransitionRouteImport } from './routes/v1/admin/orders/$id/rider-transition'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestOpenaiRoute = ApiTestOpenaiRouteImport.update({
  id: '/api/test-openai',
  path: '/api/test-openai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModuleRoute = AppModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestConnectionRoute = ApiAiTestConnectionRouteImport.update({
  id: '/api/ai/test-connection',
  path: '/api/ai/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModuleIdRoute = AppModuleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppModuleRoute,
} as any)
const V1AdminSplatRoute = V1AdminSplatRouteImport.update({
  id: '/v1/admin/$',
  path: '/v1/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminCustomerOrderRoute = V1AdminCustomerOrderRouteImport.update({
  id: '/v1/admin/customer-order',
  path: '/v1/admin/customer-order',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminCustomerOrdersRoute = V1AdminCustomerOrdersRouteImport.update({
  id: '/v1/admin/customer-orders',
  path: '/v1/admin/customer-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminMasterAiRoute = V1AdminMasterAiRouteImport.update({
  id: '/v1/admin/master-ai',
  path: '/v1/admin/master-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminRiderOffersRoute = V1AdminRiderOffersRouteImport.update({
  id: '/v1/admin/rider-offers',
  path: '/v1/admin/rider-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const V1PaymentsSplatRoute = V1PaymentsSplatRouteImport.update({
  id: '/v1/payments/$',
  path: '/v1/payments/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1TravelSplatRoute = V1TravelSplatRouteImport.update({
  id: '/v1/travel/$',
  path: '/v1/travel/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminResourceIdRoute = V1AdminResourceIdRouteImport.update({
  id: '/v1/admin/$resource/$id',
  path: '/v1/admin/$resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminCustomerOrdersIdRoute = V1AdminCustomerOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => V1AdminCustomerOrdersRoute,
} as any)
const V1AdminDispatchReassignRoute = V1AdminDispatchReassignRouteImport.update({
  id: '/v1/admin/dispatch/reassign',
  path: '/v1/admin/dispatch/reassign',
  getParentRoute: () => rootRouteImport,
} as any)
const V1AdminCustomerOrdersIdCancelRoute =
  V1AdminCustomerOrdersIdCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => V1AdminCustomerOrdersIdRoute,
  } as any)
const V1AdminOrdersIdRiderTransitionRoute =
  V1AdminOrdersIdRiderTransitionRouteImport.update({
    id: '/v1/admin/orders/$id/rider-transition',
    path: '/v1/admin/orders/$id/rider-transition',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/test-openai': typeof ApiTestOpenaiRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRouteWithChildren
  '/v1/admin/master-ai': typeof V1AdminMasterAiRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
  '/v1/travel/$': typeof V1TravelSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/customer-orders/$id': typeof V1AdminCustomerOrdersIdRouteWithChildren
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-orders/$id/cancel': typeof V1AdminCustomerOrdersIdCancelRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/test-openai': typeof ApiTestOpenaiRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRouteWithChildren
  '/v1/admin/master-ai': typeof V1AdminMasterAiRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
  '/v1/travel/$': typeof V1TravelSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/customer-orders/$id': typeof V1AdminCustomerOrdersIdRouteWithChildren
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-orders/$id/cancel': typeof V1AdminCustomerOrdersIdCancelRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/test-openai': typeof ApiTestOpenaiRoute
  '/app/$module': typeof AppModuleRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/test-connection': typeof ApiAiTestConnectionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$module/$id': typeof AppModuleIdRoute
  '/v1/admin/$': typeof V1AdminSplatRoute
  '/v1/admin/customer-order': typeof V1AdminCustomerOrderRoute
  '/v1/admin/customer-orders': typeof V1AdminCustomerOrdersRouteWithChildren
  '/v1/admin/master-ai': typeof V1AdminMasterAiRoute
  '/v1/admin/rider-offers': typeof V1AdminRiderOffersRoute
  '/v1/payments/$': typeof V1PaymentsSplatRoute
  '/v1/travel/$': typeof V1TravelSplatRoute
  '/v1/admin/$resource/$id': typeof V1AdminResourceIdRoute
  '/v1/admin/customer-orders/$id': typeof V1AdminCustomerOrdersIdRouteWithChildren
  '/v1/admin/dispatch/reassign': typeof V1AdminDispatchReassignRoute
  '/v1/admin/customer-orders/$id/cancel': typeof V1AdminCustomerOrdersIdCancelRoute
  '/v1/admin/orders/$id/rider-transition': typeof V1AdminOrdersIdRiderTransitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/test-openai'
    | '/app/$module'
    | '/app/'
    | '/api/ai/chat'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/customer-order'
    | '/v1/admin/customer-orders'
    | '/v1/admin/master-ai'
    | '/v1/admin/rider-offers'
    | '/v1/payments/$'
    | '/v1/travel/$'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/customer-orders/$id'
    | '/v1/admin/dispatch/reassign'
    | '/v1/admin/customer-orders/$id/cancel'
    | '/v1/admin/orders/$id/rider-transition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/test-openai'
    | '/app/$module'
    | '/app'
    | '/api/ai/chat'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/customer-order'
    | '/v1/admin/customer-orders'
    | '/v1/admin/master-ai'
    | '/v1/admin/rider-offers'
    | '/v1/payments/$'
    | '/v1/travel/$'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/customer-orders/$id'
    | '/v1/admin/dispatch/reassign'
    | '/v1/admin/customer-orders/$id/cancel'
    | '/v1/admin/orders/$id/rider-transition'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/test-openai'
    | '/app/$module'
    | '/app/'
    | '/api/ai/chat'
    | '/api/ai/test-connection'
    | '/api/auth/$'
    | '/app/$module/$id'
    | '/v1/admin/$'
    | '/v1/admin/customer-order'
    | '/v1/admin/customer-orders'
    | '/v1/admin/master-ai'
    | '/v1/admin/rider-offers'
    | '/v1/payments/$'
    | '/v1/travel/$'
    | '/v1/admin/$resource/$id'
    | '/v1/admin/customer-orders/$id'
    | '/v1/admin/dispatch/reassign'
    | '/v1/admin/customer-orders/$id/cancel'
    | '/v1/admin/orders/$id/rider-transition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiTestOpenaiRoute: typeof ApiTestOpenaiRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiTestConnectionRoute: typeof ApiAiTestConnectionRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  V1AdminSplatRoute: typeof V1AdminSplatRoute
  V1AdminCustomerOrderRoute: typeof V1AdminCustomerOrderRoute
  V1AdminCustomerOrdersRoute: typeof V1AdminCustomerOrdersRouteWithChildren
  V1AdminMasterAiRoute: typeof V1AdminMasterAiRoute
  V1AdminRiderOffersRoute: typeof V1AdminRiderOffersRoute
  V1PaymentsSplatRoute: typeof V1PaymentsSplatRoute
  V1TravelSplatRoute: typeof V1TravelSplatRoute
  V1AdminResourceIdRoute: typeof V1AdminResourceIdRoute
  V1AdminDispatchReassignRoute: typeof V1AdminDispatchReassignRoute
  V1AdminOrdersIdRiderTransitionRoute: typeof V1AdminOrdersIdRiderTransitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-openai': {
      id: '/api/test-openai'
      path: '/api/test-openai'
      fullPath: '/api/test-openai'
      preLoaderRoute: typeof ApiTestOpenaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$module': {
      id: '/app/$module'
      path: '/$module'
      fullPath: '/app/$module'
      preLoaderRoute: typeof AppModuleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/test-connection': {
      id: '/api/ai/test-connection'
      path: '/api/ai/test-connection'
      fullPath: '/api/ai/test-connection'
      preLoaderRoute: typeof ApiAiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$module/$id': {
      id: '/app/$module/$id'
      path: '/$id'
      fullPath: '/app/$module/$id'
      preLoaderRoute: typeof AppModuleIdRouteImport
      parentRoute: typeof AppModuleRoute
    }
    '/v1/admin/$': {
      id: '/v1/admin/$'
      path: '/v1/admin/$'
      fullPath: '/v1/admin/$'
      preLoaderRoute: typeof V1AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-order': {
      id: '/v1/admin/customer-order'
      path: '/v1/admin/customer-order'
      fullPath: '/v1/admin/customer-order'
      preLoaderRoute: typeof V1AdminCustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-orders': {
      id: '/v1/admin/customer-orders'
      path: '/v1/admin/customer-orders'
      fullPath: '/v1/admin/customer-orders'
      preLoaderRoute: typeof V1AdminCustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/master-ai': {
      id: '/v1/admin/master-ai'
      path: '/v1/admin/master-ai'
      fullPath: '/v1/admin/master-ai'
      preLoaderRoute: typeof V1AdminMasterAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/rider-offers': {
      id: '/v1/admin/rider-offers'
      path: '/v1/admin/rider-offers'
      fullPath: '/v1/admin/rider-offers'
      preLoaderRoute: typeof V1AdminRiderOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/payments/$': {
      id: '/v1/payments/$'
      path: '/v1/payments/$'
      fullPath: '/v1/payments/$'
      preLoaderRoute: typeof V1PaymentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/travel/$': {
      id: '/v1/travel/$'
      path: '/v1/travel/$'
      fullPath: '/v1/travel/$'
      preLoaderRoute: typeof V1TravelSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/$resource/$id': {
      id: '/v1/admin/$resource/$id'
      path: '/v1/admin/$resource/$id'
      fullPath: '/v1/admin/$resource/$id'
      preLoaderRoute: typeof V1AdminResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-orders/$id': {
      id: '/v1/admin/customer-orders/$id'
      path: '/$id'
      fullPath: '/v1/admin/customer-orders/$id'
      preLoaderRoute: typeof V1AdminCustomerOrdersIdRouteImport
      parentRoute: typeof V1AdminCustomerOrdersRoute
    }
    '/v1/admin/dispatch/reassign': {
      id: '/v1/admin/dispatch/reassign'
      path: '/v1/admin/dispatch/reassign'
      fullPath: '/v1/admin/dispatch/reassign'
      preLoaderRoute: typeof V1AdminDispatchReassignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/admin/customer-orders/$id/cancel': {
      id: '/v1/admin/customer-orders/$id/cancel'
      path: '/cancel'
      fullPath: '/v1/admin/customer-orders/$id/cancel'
      preLoaderRoute: typeof V1AdminCustomerOrdersIdCancelRouteImport
      parentRoute: typeof V1AdminCustomerOrdersIdRoute
    }
    '/v1/admin/orders/$id/rider-transition': {
      id: '/v1/admin/orders/$id/rider-transition'
      path: '/v1/admin/orders/$id/rider-transition'
      fullPath: '/v1/admin/orders/$id/rider-transition'
      preLoaderRoute: typeof V1AdminOrdersIdRiderTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppModuleRouteChildren {
  AppModuleIdRoute: typeof AppModuleIdRoute
}

const AppModuleRouteChildren: AppModuleRouteChildren = {
  AppModuleIdRoute: AppModuleIdRoute,
}

const AppModuleRouteWithChildren = AppModuleRoute._addFileChildren(
  AppModuleRouteChildren,
)

interface AppRouteRouteChildren {
  AppModuleRoute: typeof AppModuleRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppModuleRoute: AppModuleRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface V1AdminCustomerOrdersIdRouteChildren {
  V1AdminCustomerOrdersIdCancelRoute: typeof V1AdminCustomerOrdersIdCancelRoute
}

const V1AdminCustomerOrdersIdRouteChildren: V1AdminCustomerOrdersIdRouteChildren =
  {
    V1AdminCustomerOrdersIdCancelRoute: V1AdminCustomerOrdersIdCancelRoute,
  }

const V1AdminCustomerOrdersIdRouteWithChildren =
  V1AdminCustomerOrdersIdRoute._addFileChildren(
    V1AdminCustomerOrdersIdRouteChildren,
  )

interface V1AdminCustomerOrdersRouteChildren {
  V1AdminCustomerOrdersIdRoute: typeof V1AdminCustomerOrdersIdRouteWithChildren
}

const V1AdminCustomerOrdersRouteChildren: V1AdminCustomerOrdersRouteChildren = {
  V1AdminCustomerOrdersIdRoute: V1AdminCustomerOrdersIdRouteWithChildren,
}

const V1AdminCustomerOrdersRouteWithChildren =
  V1AdminCustomerOrdersRoute._addFileChildren(
    V1AdminCustomerOrdersRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiTestOpenaiRoute: ApiTestOpenaiRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiTestConnectionRoute: ApiAiTestConnectionRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  V1AdminSplatRoute: V1AdminSplatRoute,
  V1AdminCustomerOrderRoute: V1AdminCustomerOrderRoute,
  V1AdminCustomerOrdersRoute: V1AdminCustomerOrdersRouteWithChildren,
  V1AdminMasterAiRoute: V1AdminMasterAiRoute,
  V1AdminRiderOffersRoute: V1AdminRiderOffersRoute,
  V1PaymentsSplatRoute: V1PaymentsSplatRoute,
  V1TravelSplatRoute: V1TravelSplatRoute,
  V1AdminResourceIdRoute: V1AdminResourceIdRoute,
  V1AdminDispatchReassignRoute: V1AdminDispatchReassignRoute,
  V1AdminOrdersIdRiderTransitionRoute: V1AdminOrdersIdRiderTransitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
