-- 0019: immutable evidence ledger + target growth primitives
-- Non-destructive: adds append-only evidence and incentive tables only.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS immutable_event_chain_state (
  id SMALLINT PRIMARY KEY CHECK (id = 1),
  last_hash TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

INSERT INTO immutable_event_chain_state (id, last_hash)
VALUES (1, repeat('0', 64))
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS immutable_event_ledger (
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  source_schema TEXT NOT NULL,
  source_table TEXT NOT NULL,
  source_operation TEXT NOT NULL CHECK (source_operation IN ('INSERT','UPDATE','DELETE')),
  source_id TEXT NOT NULL,
  org_id TEXT,
  occurred_at TIMESTAMPTZ NOT NULL,
  payload JSONB NOT NULL,
  previous_hash TEXT NOT NULL,
  event_hash TEXT NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS immutable_event_org_time_idx
  ON immutable_event_ledger (org_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS immutable_event_source_idx
  ON immutable_event_ledger (source_table, source_id, occurred_at DESC);

CREATE OR REPLACE FUNCTION public.capture_immutable_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  payload JSONB;
  source_id TEXT;
  org_id_value TEXT;
  previous_value TEXT;
  event_hash_value TEXT;
  event_time TIMESTAMPTZ := clock_timestamp();
BEGIN
  payload := CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END;
  source_id := COALESCE(
    payload->>'id',
    payload->>'entry_id',
    payload->>'transaction_id',
    payload->>'batch_id',
    payload->>'event_id',
    md5(payload::TEXT)
  );
  org_id_value := payload->>'org_id';

  IF TG_TABLE_NAME = 'rider_location_pings' THEN
    payload := jsonb_strip_nulls(jsonb_build_object(
      'id', payload->>'id',
      'rider_id', payload->>'rider_id',
      'order_id', payload->>'order_id',
      'lat', payload->>'lat',
      'lng', payload->>'lng',
      'accuracy', payload->>'accuracy',
      'recorded_at', payload->>'recorded_at',
      'operation', TG_OP
    ));
  END IF;

  SELECT last_hash
  INTO previous_value
  FROM immutable_event_chain_state
  WHERE id = 1
  FOR UPDATE;

  event_hash_value := encode(
    digest(
      TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME || '|' ||
      TG_OP || '|' || source_id || '|' ||
      event_time::TEXT || '|' ||
      COALESCE(org_id_value, '') || '|' ||
      payload::TEXT || '|' ||
      previous_value,
      'sha256'
    ),
    'hex'
  );

  INSERT INTO immutable_event_ledger (
    source_schema, source_table, source_operation, source_id,
    org_id, occurred_at, payload, previous_hash, event_hash
  )
  VALUES (
    TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_OP, source_id,
    org_id_value, event_time, payload, previous_value, event_hash_value
  );

  UPDATE immutable_event_chain_state
  SET last_hash = event_hash_value, updated_at = event_time
  WHERE id = 1;

  RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE OR REPLACE FUNCTION public.prevent_immutable_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  RAISE EXCEPTION 'IMMUTABLE_LEDGER_WRITE_BLOCKED';
END;
$$;

DROP TRIGGER IF EXISTS immutable_event_ledger_guard_update ON immutable_event_ledger;
CREATE TRIGGER immutable_event_ledger_guard_update
BEFORE UPDATE OR DELETE ON immutable_event_ledger
FOR EACH ROW EXECUTE FUNCTION public.prevent_immutable_event_mutation();

REVOKE UPDATE, DELETE, TRUNCATE ON immutable_event_ledger FROM PUBLIC;
REVOKE UPDATE, DELETE, TRUNCATE ON immutable_event_ledger FROM anon;
REVOKE UPDATE, DELETE, TRUNCATE ON immutable_event_ledger FROM authenticated;

DO $$
DECLARE
  target_table TEXT;
  trigger_name TEXT;
BEGIN
  FOREACH target_table IN ARRAY ARRAY[
    'orders',
    'order_events',
    'payments',
    'ledger_transactions',
    'ledger_entries',
    'settlement_batches',
    'audit_logs',
    'rider_location_pings',
    'kingpay_wallets',
    'kingpay_transactions',
    'payment_webhook_events'
  ]
  LOOP
    IF to_regclass('public.' || quote_ident(target_table)) IS NOT NULL THEN
      trigger_name := 'immutable_' || target_table || '_capture';
      EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', trigger_name, target_table);
      EXECUTE format(
        'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.capture_immutable_event()',
        trigger_name, target_table
      );
    END IF;
  END LOOP;
END
$$;

CREATE TABLE IF NOT EXISTS growth_campaigns (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  name TEXT NOT NULL,
  participant_type TEXT NOT NULL CHECK (participant_type IN ('CUSTOMER','RESTAURANT','RIDER','MERCHANT')),
  target_metric TEXT NOT NULL CHECK (target_metric IN ('QUALIFIED_REFERRALS','FIRST_ORDERS','SHARES','DELIVERED_ORDERS')),
  target_value BIGINT NOT NULL CHECK (target_value > 0),
  reward_paise BIGINT NOT NULL DEFAULT 0 CHECK (reward_paise >= 0),
  reward_coins BIGINT NOT NULL DEFAULT 0 CHECK (reward_coins >= 0),
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','PAUSED','COMPLETED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS growth_attributions (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  campaign_id TEXT REFERENCES growth_campaigns(id),
  referral_code TEXT NOT NULL,
  referrer_type TEXT NOT NULL CHECK (referrer_type IN ('CUSTOMER','RESTAURANT','RIDER','MERCHANT')),
  referrer_id TEXT NOT NULL,
  referred_user_id TEXT NOT NULL,
  first_qualified_order_id TEXT,
  qualified_at TIMESTAMPTZ,
  reward_status TEXT NOT NULL DEFAULT 'PENDING' CHECK (reward_status IN ('PENDING','QUALIFIED','REWARDED','REJECTED')),
  fraud_score INTEGER NOT NULL DEFAULT 0 CHECK (fraud_score BETWEEN 0 AND 100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (referral_code, referred_user_id)
);

CREATE INDEX IF NOT EXISTS growth_attribution_referrer_idx
  ON growth_attributions (referrer_type, referrer_id, created_at DESC);

CREATE TABLE IF NOT EXISTS growth_reward_events (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  campaign_id TEXT NOT NULL REFERENCES growth_campaigns(id),
  actor_type TEXT NOT NULL CHECK (actor_type IN ('CUSTOMER','RESTAURANT','RIDER','MERCHANT')),
  actor_id TEXT NOT NULL,
  threshold_value BIGINT NOT NULL,
  reward_paise BIGINT NOT NULL DEFAULT 0 CHECK (reward_paise >= 0),
  reward_coins BIGINT NOT NULL DEFAULT 0 CHECK (reward_coins >= 0),
  idempotency_key TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPLIED','BLOCKED')),
  evidence_event_id UUID REFERENCES immutable_event_ledger(event_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  applied_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS growth_reward_actor_idx
  ON growth_reward_events (actor_type, actor_id, created_at DESC);
