ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on app_config" ON public.app_config FOR ALL USING (false);
CREATE POLICY "Service role bypass on app_config" ON public.app_config FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on cities" ON public.cities FOR ALL USING (false);
CREATE POLICY "Service role bypass on cities" ON public.cities FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.service_zones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on service_zones" ON public.service_zones FOR ALL USING (false);
CREATE POLICY "Service role bypass on service_zones" ON public.service_zones FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on categories" ON public.categories FOR ALL USING (false);
CREATE POLICY "Service role bypass on categories" ON public.categories FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on restaurants" ON public.restaurants FOR ALL USING (false);
CREATE POLICY "Service role bypass on restaurants" ON public.restaurants FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.restaurant_outlets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on restaurant_outlets" ON public.restaurant_outlets FOR ALL USING (false);
CREATE POLICY "Service role bypass on restaurant_outlets" ON public.restaurant_outlets FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.restaurant_hours ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on restaurant_hours" ON public.restaurant_hours FOR ALL USING (false);
CREATE POLICY "Service role bypass on restaurant_hours" ON public.restaurant_hours FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.restaurant_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on restaurant_categories" ON public.restaurant_categories FOR ALL USING (false);
CREATE POLICY "Service role bypass on restaurant_categories" ON public.restaurant_categories FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on menu_categories" ON public.menu_categories FOR ALL USING (false);
CREATE POLICY "Service role bypass on menu_categories" ON public.menu_categories FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on menu_items" ON public.menu_items FOR ALL USING (false);
CREATE POLICY "Service role bypass on menu_items" ON public.menu_items FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.menu_variants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on menu_variants" ON public.menu_variants FOR ALL USING (false);
CREATE POLICY "Service role bypass on menu_variants" ON public.menu_variants FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.addon_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on addon_groups" ON public.addon_groups FOR ALL USING (false);
CREATE POLICY "Service role bypass on addon_groups" ON public.addon_groups FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.addons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on addons" ON public.addons FOR ALL USING (false);
CREATE POLICY "Service role bypass on addons" ON public.addons FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on promotions" ON public.promotions FOR ALL USING (false);
CREATE POLICY "Service role bypass on promotions" ON public.promotions FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on profiles" ON public.profiles FOR ALL USING (false);
CREATE POLICY "Service role bypass on profiles" ON public.profiles FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on customer_addresses" ON public.customer_addresses FOR ALL USING (false);
CREATE POLICY "Service role bypass on customer_addresses" ON public.customer_addresses FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on orders" ON public.orders FOR ALL USING (false);
CREATE POLICY "Service role bypass on orders" ON public.orders FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on order_items" ON public.order_items FOR ALL USING (false);
CREATE POLICY "Service role bypass on order_items" ON public.order_items FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.order_price_lines ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on order_price_lines" ON public.order_price_lines FOR ALL USING (false);
CREATE POLICY "Service role bypass on order_price_lines" ON public.order_price_lines FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.order_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on order_events" ON public.order_events FOR ALL USING (false);
CREATE POLICY "Service role bypass on order_events" ON public.order_events FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on payments" ON public.payments FOR ALL USING (false);
CREATE POLICY "Service role bypass on payments" ON public.payments FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on refunds" ON public.refunds FOR ALL USING (false);
CREATE POLICY "Service role bypass on refunds" ON public.refunds FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.promotion_redemptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on promotion_redemptions" ON public.promotion_redemptions FOR ALL USING (false);
CREATE POLICY "Service role bypass on promotion_redemptions" ON public.promotion_redemptions FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.loyalty_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on loyalty_accounts" ON public.loyalty_accounts FOR ALL USING (false);
CREATE POLICY "Service role bypass on loyalty_accounts" ON public.loyalty_accounts FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.loyalty_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on loyalty_transactions" ON public.loyalty_transactions FOR ALL USING (false);
CREATE POLICY "Service role bypass on loyalty_transactions" ON public.loyalty_transactions FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.favourites ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on favourites" ON public.favourites FOR ALL USING (false);
CREATE POLICY "Service role bypass on favourites" ON public.favourites FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.favourite_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on favourite_items" ON public.favourite_items FOR ALL USING (false);
CREATE POLICY "Service role bypass on favourite_items" ON public.favourite_items FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on support_tickets" ON public.support_tickets FOR ALL USING (false);
CREATE POLICY "Service role bypass on support_tickets" ON public.support_tickets FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on notifications" ON public.notifications FOR ALL USING (false);
CREATE POLICY "Service role bypass on notifications" ON public.notifications FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.notification_outbox ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on notification_outbox" ON public.notification_outbox FOR ALL USING (false);
CREATE POLICY "Service role bypass on notification_outbox" ON public.notification_outbox FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on analytics_events" ON public.analytics_events FOR ALL USING (false);
CREATE POLICY "Service role bypass on analytics_events" ON public.analytics_events FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on audit_logs" ON public.audit_logs FOR ALL USING (false);
CREATE POLICY "Service role bypass on audit_logs" ON public.audit_logs FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.otp_challenges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on otp_challenges" ON public.otp_challenges FOR ALL USING (false);
CREATE POLICY "Service role bypass on otp_challenges" ON public.otp_challenges FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.restaurant_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on restaurant_members" ON public.restaurant_members FOR ALL USING (false);
CREATE POLICY "Service role bypass on restaurant_members" ON public.restaurant_members FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');
ALTER TABLE public.riders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Deny all for public on riders" ON public.riders FOR ALL USING (false);
CREATE POLICY "Service role bypass on riders" ON public.riders FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

-- Base Isolation (RBAC/RLS) initialized as DENY ALL to enforce Secure-by-Default.

